<?php
function gwc_coupable_haut_min_14_oi($code){switch($code){
case'oiidioiiioiiol':return array('audiovisuel');
case'oiiomoototiooo':return array('augmentations');
case'oiitoooitioiio':return array('autocritique');
case'oiitooiiiooiio':return array('autocuiseur');
case'oiitomotioiioo':return array('automatiques');
case'oiitomohiliomo':return array('automobilisme');
case'oiitomohilioto':return array('automobiliste');
case'oiitooiootiooo':return array('autorisations');
case'oiiootooodioto':return array('avantgardiste');
case'oiiootiiooiiii':return array('aventureux');
case'oiiootiooomoot':return array('avertissement');
case'oiooooooootioo':return array('circonspection');
case'oiiiiliootiooo':return array('civilisations');
case'oiiltiiiotoiio':return array('cultivateur');
case'oiiltiiiotoioo':return array('cultivatrice');
case'oiioioiioomoot':return array('curieusement');
case'oiioiithmioiio':return array('eurythmique');
case'oiioootioooolo':return array('exceptionnels');
case'oiioliioiiiito':return array('exclusivite');
case'oiioooimootolo':return array('experimentale');
case'oiiolioitomoot':return array('explicitement');
case'oiioloitotiooo':return array('exploitations');
case'oiiooototoiioo':return array('exportateurs');
case'oiitoooiioiioo':return array('extorqueuse');
case'oioooiimoiioho':return array('oiseaumouche');
case'oiihlioitoiooo':return array('publicitaires');
case'oiihlioiiomoot':return array('publiquement');
case'oiiolifiootioo':return array('qualification');
case'oiiootiooooioo':return array('questionnaire');
case'oidooiiooiotoo':return array('siderurgistes');
case'oiooifiootiiio':return array('significative');
case'oimolifiootioo':return array('simplification');
case'oimiiltooomoot':return array('simultanement');
case'oiihoodiootioo':return array('subordination');
case'oiihotootiollo':return array('substantielle');
case'oiihotitiitioo':return array('substitution');
case'oiiooiootomoot':return array('succinctement');
case'oiioooiiiooiio':return array('superviseur');
case'oiioiioilloooo':return array('surveillance');
case'oiioiioillooto':return array('surveillants');
case'oiimoothioooto':return array('sympathisants');
case'oiiodiooliotoo':return array('syndicalistes');
case'oiiotomotioiio':return array('systematique');
default: return array();}}
?>