<?php
function gwc_coupable_haut_min_6_io($code){switch($code){
case'ioihoo':return array('icibas');
case'iotooo':return array('ictere','jetons');
case'iooooo':return array('ignare','ignore','insere','japper','jargon','jeanne');
case'ioooto':return array('inapte','inepte','inerte');
case'iooito':return array('incite','irrite');
case'iodoii':return array('index');
case'iodioo':return array('indice','indien');
case'ioodit':return array('inedit');
case'iooool':return array('inegal','irreel','israel');
case'iofomo':return array('infame');
case'iofoot':return array('infect');
case'iofimo':return array('infime');
case'iofioi':return array('infini');
case'ioooot':return array('ingrat','jarret');
case'ioitio':return array('initie');
case'iooiii':return array('inoui');
case'iootoo':return array('instar');
case'iotoot':return array('intact','jetant');
case'iotimo':return array('intime');
case'ioiioi':return array('iouri');
case'ioooio':return array('ironie','jospin');
case'iolood':return array('island');
case'iooloo':return array('isolee','isoler','isoles');
case'iooiio':return array('issue','issus','jesus');
case'ioohii':return array('jacky');
case'iomoio':return array('jamais');
case'iomhoo':return array('jambes','jambon');
case'ioodio':return array('jardin');
case'ioiioo':return array('jauge','jaune','jeune','joker','jouee','jouer','jours','joyce');
case'ioiiol':return array('javel');
case'iooomo':return array('jerome');
case'iotoit':return array('jetait');
case'ioiidi':return array('jeudi');
case'ioiiii':return array('jeux');
case'ioollo':return array('joelle');
case'ioioto':return array('joints');
case'iooooh':return array('joseph');
case'ioiiot':return array('jouet');
case'ioiiio':return array('jouir');
case'ioiiit':return array('jouit');
default: return array();}}
?>