<?php
function gwc_coupable_haut_min_6_oh($code){switch($code){
case'ohooio':return array('abasie','cherir','chopin');
case'ohotio':return array('abetir');
case'ohimoo':return array('abimer','shimon');
case'ohioot':return array('abject','chiant','chipot');
case'oholio':return array('abolir');
case'ohoooo':return array('abonne','abrege','chance','change','chapon','charge','chasse','cheres','choper','choses','phares','phases','phones','phrase');
case'ohoodo':return array('aborde','abords');
case'ohoiit':return array('about');
case'ohoito':return array('abrite');
case'ohooot':return array('absent','chenet');
case'ohodli':return array('chadli');
case'ohoioo':return array('chaine','chaire','chairs','chaise');
case'oholot':return array('chalet','cholet');
case'ohomoo':return array('champs');
case'ohooto':return array('chante','chants','charte','chaste','ehonte');
case'ohoomo':return array('charme');
case'ohoiid':return array('chaud');
case'ohoihh':return array('cheikh');
case'oholom':return array('chelem');
case'ohomio':return array('chemin','shamir');
case'ohotif':return array('chetif');
case'ohiood':return array('chiard');
case'ohiooo':return array('chicon','chiens','chiper','chirac','chiron');
case'ohiito':return array('chiite','chute');
case'ohimio':return array('chimie');
case'ohioio':return array('chipie');
case'ohlooo':return array('chlore');
case'ohoioi':return array('choisi');
case'ohoiii':return array('choix','show');
case'ohoiot':return array('christ');
case'ohohio':return array('ebahir');
case'ohotto':return array('ghetto');
case'ohioto':return array('objets');
case'ohlioo':return array('oblige');
case'ohtiio':return array('obtus');
case'ohilio':return array('philip');
case'ohotoo':return array('photos');
case'ohiimo':return array('rhume');
default: return array();}}
?>