<?php
function gwc_coupable_haut_min_6_ol($code){switch($code){
case'oloomo':return array('alarme');
case'olhoot':return array('albert');
case'olhiim':return array('album');
case'olooli':return array('alcali');
case'oloool':return array('alcool');
case'olooto':return array('alerte','clarte','plante');
case'olfood':return array('alfred');
case'oloiio':return array('algue','eleve','plouc');
case'oliooo':return array('aliene','aligne','alinea','glisse');
case'olloio':return array('allais');
case'olloit':return array('allait');
case'olloot':return array('allant');
case'ollooo':return array('allees','allege','allons');
case'ollioo':return array('alliee','allier','allies');
case'oloooo':return array('alpage','alsace','classe','clerge','elance','eloges','glacer','glacon','gloser','placee','placer','places','plages','planer','plonge','slogan');
case'oltioo':return array('altier');
case'oloioo':return array('claire','clairs','glaise','gloire','plaies','plaine','plaire','pleine','pleins');
case'olomoo':return array('clamer');
case'olooii':return array('clark');
case'olioho':return array('cliche');
case'olioot':return array('client');
case'olimot':return array('climat');
case'olooho':return array('cloche');
case'oloiid':return array('cloud');
case'oliiho':return array('clubs');
case'oloooi':return array('elargi');
case'olimoo':return array('elimer');
case'olitoo':return array('elites');
case'oloodo':return array('glande');
case'olooio':return array('glapir');
case'olohol':return array('global');
case'oliiio':return array('olive','pluie');
case'oloido':return array('plaide');
case'oloiot':return array('plaint');
case'olotoo':return array('plates','platon','platre');
case'oliimo':return array('plume');
default: return array();}}
?>