<?php
function gwc_coupable_bas_maj_5_II($code){switch($code){
case'IIOOL':return array('abbe','acul','asse','aube','auge','figue','noce','noue','robe','rose','roue','rude','ruse','tisse');
case'IIOOO':return array('abus','hugo','nous','tissu');
case'IIOIL':return array('acte','asie','hote','note','noye','piste');
case'IILIL':return array('acte','neil','piete');
case'IILOL':return array('acul','piece','piege','tiede','tilde');
case'IIOII':return array('adn','agit','aux','huit','hun','non','nuit','pion');
case'IIOLL':return array('agee','fidel','noce','noel','nuee','role','ruee');
case'IIOLO':return array('ages','nues','nuls','rues');
case'IIIOL':return array('aide','aise','face','fade','froc','inde','nice','page','paul','ride','troc','truc');
case'IIIOO':return array('aigu','fado','froc','insu','mou','prou','titus','troc','trou','truc');
case'IIILL':return array('aile','face','mec','nice','pale');
case'IIIII':return array('ain','air','aix','art','fait','fan','fax','fiat','fini','ina','ira','ma','mit','pan','papy','par','prit','rai','ray','tati','yak');
case'IILLL':return array('alle','fille','piece','reel');
case'IILLO':return array('allo','files','nees','recu','reed');
case'IILIO':return array('alto','nets','repu','rets');
case'IIIIO':return array('anc','ans','arc','fais','fins','fric','has','info','iris','mis','pays','pins','pris','rad','ras','this','tirs','trio');
case'IIIIL':return array('anc','ane','apte','arc','are','axe','fail','fine','fixe','fric','mie','mil','paie','pape','pate','paye','pire','pitie','prie','rite','taie','tape','tire');
case'IIOOI':return array('aout','roui');
case'IIOIO':return array('auto','huis','rois');
case'IIVLO':return array('avec','aveu');
case'IIVLL':return array('avec');
case'IIVLZ':return array('avez');
case'IIVIO':return array('avis');
case'IIIOI':return array('faut','moi','mot','prof','tact','trop');
case'IILII':return array('fier','rer','tien');
case'IILLI':return array('filet');
case'IILOO':return array('filou','pieds','recu');
case'IIILO':return array('fred','kilo','mec','mes','pneu','pres','theo','tres','types');
case'IIILI':return array('fret','kilt','met','pret','tact');
case'IIILV':return array('kiev');
case'IILOI':return array('neuf','pilot');
case'IIIVL':return array('pave','rive');
case'IIQOL':return array('pique');
case'IIVOI':return array('pivot');
case'IILVL':return array('reve');
case'IILVO':return array('revu');
case'IIOLI':return array('tibet');
default: return array();}}
?>