<?php
function gwc_centrale_5_PB($code){switch($code){
case'PBABB':return array('peage','pence','pense','perec','peres');
case'PBBHB':return array('peche','poche');
case'PBBAB':return array('pedro','pegre');
case'PBIAB':return array('peine','poing','poire');
case'PBIAT':return array('peint','point');
case'PBHIA':return array('pekin');
case'PBLBA':return array('peler');
case'PBLLB':return array('pelle');
case'PBAAL':return array('penal');
case'PBABU':return array('pendu','percu','perdu','perou');
case'PBAIB':return array('penis');
case'PBAAB':return array('penne');
case'PBATB':return array('pente','perte','ponts','porte','porto','ports');
case'PBATU':return array('pentu');
case'PBPIA':return array('pepin');
case'PBAIL':return array('peril');
case'PBAIA':return array('perir');
case'PBALB':return array('perle');
case'PBAMB':return array('perme');
case'PBBBA':return array('peser','poser');
case'PBBTB':return array('peste','poete','poste');
case'PBTBA':return array('peter');
case'PBTIT':return array('petit');
case'PBTAB':return array('petre');
case'PBTAI':return array('petri');
case'PBUHL':return array('peuhl');
case'PBBLB':return array('poele');
case'PBBMB':return array('poeme');
case'PBHBA':return array('poher');
case'PBIBB':return array('poids');
case'PBLAA':return array('polar');
case'PBLBB':return array('poles');
case'PBLIA':return array('polir');
case'PBMMB':return array('pomme');
case'PBMPB':return array('pompe');
case'PBABY':return array('poney');
case'PBATA':return array('porta');
case'PBBBB':return array('posee','poses');
case'PBTBB':return array('potes');
case'PBTIA':return array('potin');
case'PBUBB':return array('pouce');
case'PBULB':return array('poule','pouls');
case'PBUPB':return array('poupe');
default: return array();}}
?>