<?php
function gwc_centrale_5_VB($code){switch($code){
case'VBBUB':return array('vecue','vogue');
case'VBIAB':return array('veine','voire');
case'VBABU':return array('vendu');
case'VBABZ':return array('venez');
case'VBAIA':return array('venin','venir');
case'VBATB':return array('vente','vents','verte','verts');
case'VBAUB':return array('venue','venus');
case'VBABB':return array('verbe','verge','verse','verso');
case'VBAAB':return array('verne','verre');
case'VBAAI':return array('verni');
case'VBAAA':return array('verra');
case'VBATU':return array('vertu');
case'VBAVB':return array('verve');
case'VBBTB':return array('veste');
case'VBTIA':return array('vetir');
case'VBTUB':return array('vetus');
case'VBULB':return array('veule');
case'VBUVB':return array('veuve');
case'VBHBA':return array('vexer');
case'VBBHA':return array('vodka');
case'VBBUH':return array('voeux');
case'VBBBL':return array('vogel');
case'VBIBI':return array('voici');
case'VBIBB':return array('voies');
case'VBILB':return array('voile');
case'VBLBB':return array('volee');
case'VBLBA':return array('voler','volga');
case'VBLBT':return array('volet');
case'VBLVB':return array('volvo');
case'VBMIA':return array('vomir');
case'VBTBB':return array('votee','votes');
case'VBTBA':return array('voter');
case'VBTAB':return array('votre');
case'VBUBB':return array('vouee','voues');
case'VBUBA':return array('vouer');
case'VBULU':return array('voulu');
case'VBUTB':return array('voute');
case'VBYBZ':return array('voyez');
case'VBYBU':return array('voyou');
default: return array();}}
?>