<?php
function gwc_coupable_bas_min_20_ao($code){switch($code){
case'aoiaaiioiaaaaaaiaiii':return array('carbonatedesodium');
case'aoiaaiioaaaaaaaiaiii':return array('carbonatedesodium');
case'aoiaaiioiaoaaaaiaiii':return array('carbonatedesodium');
case'aoiaaiioaaoaaaaiaiii':return array('carbonatedesodium');
case'aoiaaiioiaaaaaoiaiii':return array('carbonatedesodium');
case'aoiaaiioaaaaaaoiaiii':return array('carbonatedesodium');
case'aoiaaiioiaoaaaoiaiii':return array('carbonatedesodium');
case'aoiaaiioaaoaaaoiaiii':return array('carbonatedesodium');
case'aoiaaiioiaaaaaaaaiii':return array('carbonatedesodium');
case'aoiaaiioaaaaaaaaaiii':return array('carbonatedesodium');
case'aoiaaiioiaoaaaaaaiii':return array('carbonatedesodium');
case'aoiaaiioaaoaaaaaaiii':return array('carbonatedesodium');
case'aoiaaiioiaaaaaoaaiii':return array('carbonatedesodium');
case'aoiaaiioaaaaaaoaaiii':return array('carbonatedesodium');
case'aoiaaiioiaoaaaoaaiii':return array('carbonatedesodium');
case'aoiaaiioaaoaaaoaaiii':return array('carbonatedesodium');
case'aoiaaiioiaaaaaaioiii':return array('carbonatedesodium');
case'aoiaaiioaaaaaaaioiii':return array('carbonatedesodium');
case'aoiaaiioiaoaaaaioiii':return array('carbonatedesodium');
case'aoiaaiioaaoaaaaioiii':return array('carbonatedesodium');
case'aoiaaiioiaaaaaoioiii':return array('carbonatedesodium');
case'aoiaaiioaaaaaaoioiii':return array('carbonatedesodium');
case'aoiaaiioiaoaaaoioiii':return array('carbonatedesodium');
case'aoiaaiioaaoaaaoioiii':return array('carbonatedesodium');
case'aoiaaiioiaaaaaaaoiii':return array('carbonatedesodium');
case'aoiaaiioaaaaaaaaoiii':return array('carbonatedesodium');
case'aoiaaiioiaoaaaaaoiii':return array('carbonatedesodium');
case'aoiaaiioaaoaaaaaoiii':return array('carbonatedesodium');
case'aoiaaiioiaaaaaoaoiii':return array('carbonatedesodium');
case'aoiaaiioaaaaaaoaoiii':return array('carbonatedesodium');
case'aoiaaiioiaoaaaoaoiii':return array('carbonatedesodium');
case'aoiaaiioaaoaaaoaoiii':return array('carbonatedesodium');
case'aoiiiaaaiiiiaiiiaiii':return array('tambourinement');
case'aoiiiaaoiiiiaiiiaiii':return array('tambourinement');
case'aoiiiaaaiaiiaiiiaiii':return array('tambourinement');
case'aoiiiaaoiaiiaiiiaiii':return array('tambourinement');
case'aoiiiaaaiiiiaiiiaiia':return array('tambourinement');
case'aoiiiaaoiiiiaiiiaiia':return array('tambourinement');
case'aoiiiaaaiaiiaiiiaiia':return array('tambourinement');
case'aoiiiaaoiaiiaiiiaiia':return array('tambourinement');
default: return array();}}
?>