<?php
function gwc_coupable_bas_maj_18_OI($code){switch($code){
case'OIIIIIIIOOLIIILIII':return array('bannissement');
case'OIIOIIIOIIIIIIILII':return array('baumgartner');
case'OIIILLIIIIIIIILIII':return array('brillamment');
case'OIILIIOIIIIILIIIIL':return array('californienne');
case'OIIIIIIIIIIIOLIIIL':return array('camaraderie');
case'OIIIIIIIIOIIIIIIOL':return array('campagnarde');
case'OIIIIIIILIOIIIIOII':return array('capitalisation');
case'OIIIIIIOILIIIOLIII':return array('caracterisent');
case'OIIIIIILILIIIOLIII':return array('caracterisent');
case'OIIIIIIIIVIILLOQOL':return array('carnavalesque');
case'OIIIIIOIIIOIIIIQOL':return array('catastrophique');
case'OIIIIIIIIOLVIOIOII':return array('champdevision');
case'OIIIIIIIIIOIIIIIII':return array('championnat');
case'OIIIIIIOLOOIIIOIII':return array('chardecombat');
case'OIIIIIIOLLOIIIOIII':return array('chardecombat');
case'OIIIIOOIIOIIIIILII':return array('chaudronnier');
case'OIILIIIIIILIIILIII':return array('cheminement');
case'OIIOIILOOIIIIIIIIL':return array('dactylographie');
case'OIILIILOOIIIIIIIIL':return array('dactylographie');
case'OIIILIILIIIIIILIII':return array('differemment');
case'OIVLIIOIIIOIIIIOII':return array('diversification');
case'OIVLIIOIIILIIIIOII':return array('diversification');
case'OIVLIIIIOOLIIILIII':return array('divertissement');
case'OIIIIIIIIIIOOIIIII':return array('garantissant');
case'OIIIIOLIIIIIIIOLII':return array('gardemanger');
case'OIIOIIIOIIOIIIIQOL':return array('gastronomique');
case'OIIOOOILIILIIILIII':return array('grossierement');
case'OILIIIIIIOIIIILLLL':return array('operationnelle');
case'OIIOIIIOIILIIILIII':return array('opportunement');
case'OIIOIIIIIOIIILOIIO':return array('organisateurs');
case'OIIOIIIIIOIIIIOIIO':return array('organisations');
case'OIIILOIIIOIIIIILII':return array('sapeurpompier');
case'OIIIIILIIIOIIIIOII':return array('simplification');
case'OIIIIILIIILIIIIOII':return array('simplification');
case'OIOIIIIIIILIIILIII':return array('spontanement');
case'OIIIIIIIIIILIIIILO':return array('ukrainiennes');
case'OIIIVLIIOIIIIIIILO':return array('universitaires');
default: return array();}}
?>