<?php
function gwc_coupable_bas_maj_18_OL($code){switch($code){
case'OLIIIIIIIILIIILIII':return array('certainement');
case'OLIIOOIIIOIIIIOIIO':return array('classifications');
case'OLIIOOIIILIIIIOIIO':return array('classifications');
case'OLOIIIIIIILIIILIII':return array('dechainement','desarmement');
case'OLLIIIIIIILIIILIII':return array('dechainement');
case'OLOLLIIOIILIIILIII':return array('declenchement');
case'OLLLLIIOIILIIILIII':return array('declenchement');
case'OLOLLIILIILIIILIII':return array('declenchement');
case'OLLLLIILIILIIILIII':return array('declenchement');
case'OLOOIIILIIIIIIOLII':return array('decontenancer');
case'OLLOIIILIIIIIIOLII':return array('decontenancer');
case'OLOOIIILIIIIIILLII':return array('decontenancer');
case'OLLOIIILIIIIIILLII':return array('decontenancer');
case'OLOOOIIIIOLIIILIII':return array('decouragement');
case'OLLOOIIIIOLIIILIII':return array('decouragement');
case'OLIIIIIIIVLIIILIII':return array('definitivement');
case'OLIIIIIIIOLIIIOOII':return array('demangeaison');
case'OLIIILOOIILIIILIII':return array('demesurement');
case'OLIIIOOIIIIIIIIQOL':return array('demographique');
case'OLIIOIIIIIIIIIIOII':return array('denomination');
case'OLILIIIILIOIIIIOII':return array('depenalisation');
case'OLIIIIIOOIIIIIIOLL':return array('deraisonnable');
case'OLIIIIILIILIIILIII':return array('dernierement');
case'OLOIIIIIIOOIIILOII':return array('desapprobateur');
case'OLOIIIIIIOOIIIIOII':return array('desapprobation');
case'OLOIIVIIIIIIIOLOII':return array('desavantageux');
case'OLOLIIOIIOLIIILIII':return array('desengagement');
case'OLOIIIOILIOIIIIOII':return array('destabilisation');
case'OLILIIIIIIIIIIIIIL':return array('determinante');
case'OLIOOIIIILIIILIIIO':return array('detournements');
case'OLOIOOIILIIIIIIIII':return array('deutschemark');
case'OLOIOLIILIIIIIIIII':return array('deutschemark');
case'OLOIIILIIILIIILIII':return array('deuxiemement');
case'OLIILIIIILLIIILIII':return array('generalement');
case'OLIILIILOOLIIILIII':return array('genereusement');
case'OLIIIIIIIIIOIIILII':return array('scaphandrier');
case'OLLIILOLIIILIIIIIL':return array('scenedetheatre');
case'OLIIOIOILIOIIIIOII':return array('sensibilisation');
default: return array();}}
?>