<?php
function gwc_coupable_bas_min_16_jo($code){switch($code){
case'joiiiiaaaiiiaiii':return array('jaillissement');
case'joaiiiaaaiiiaiii':return array('jaillissement','jaunissement');
case'joiiiaaaaiiiaiii':return array('jaillissement');
case'joaiiaaaaiiiaiii':return array('jaillissement','jaunissement');
case'joiiiiaaaiiiaiia':return array('jaillissement');
case'joaiiiaaaiiiaiia':return array('jaillissement','jaunissement');
case'joiiiaaaaiiiaiia':return array('jaillissement');
case'joaiiaaaaiiiaiia':return array('jaillissement','jaunissement');
case'jooiiiaaaiiiaiii':return array('jaunissement');
case'jooiiaaaaiiiaiii':return array('jaunissement');
case'jooiiiaaaiiiaiia':return array('jaunissement');
case'jooiiaaaaiiiaiia':return array('jaunissement');
case'joiiaiqaaiiiaiii':return array('juridiquement');
case'joiaaiqaaiiiaiii':return array('juridiquement');
case'joiioiqaaiiiaiii':return array('juridiquement');
case'joiaoiqaaiiiaiii':return array('juridiquement');
case'joiiaaqaaiiiaiii':return array('juridiquement');
case'joiaaaqaaiiiaiii':return array('juridiquement');
case'joiioaqaaiiiaiii':return array('juridiquement');
case'joiaoaqaaiiiaiii':return array('juridiquement');
case'joiiaiqoaiiiaiii':return array('juridiquement');
case'joiaaiqoaiiiaiii':return array('juridiquement');
case'joiioiqoaiiiaiii':return array('juridiquement');
case'joiaoiqoaiiiaiii':return array('juridiquement');
case'joiiaaqoaiiiaiii':return array('juridiquement');
case'joiaaaqoaiiiaiii':return array('juridiquement');
case'joiioaqoaiiiaiii':return array('juridiquement');
case'joiaoaqoaiiiaiii':return array('juridiquement');
case'joiiaiqaaiiiaiia':return array('juridiquement');
case'joiaaiqaaiiiaiia':return array('juridiquement');
case'joiioiqaaiiiaiia':return array('juridiquement');
case'joiaoiqaaiiiaiia':return array('juridiquement');
case'joiiaaqaaiiiaiia':return array('juridiquement');
case'joiaaaqaaiiiaiia':return array('juridiquement');
case'joiioaqaaiiiaiia':return array('juridiquement');
case'joiaoaqaaiiiaiia':return array('juridiquement');
case'joiiaiqoaiiiaiia':return array('juridiquement');
case'joiaaiqoaiiiaiia':return array('juridiquement');
case'joiioiqoaiiiaiia':return array('juridiquement');
case'joiaoiqoaiiiaiia':return array('juridiquement');
case'joiiaaqoaiiiaiia':return array('juridiquement');
case'joiaaaqoaiiiaiia':return array('juridiquement');
case'joiioaqoaiiiaiia':return array('juridiquement');
case'joiaoaqoaiiiaiia':return array('juridiquement');
default: return array();}}
?>