<?php
function gwc_coupable_bas_min_6_gi($code){switch($code){
case'gioaai':return array('giaour','glacer');
case'gioaoi':return array('giaour');
case'giaiai':return array('gibier');
case'giaaai':return array('gibier','gloser','griser');
case'giiiai':return array('gifler');
case'gigaia':return array('gigots');
case'gigaaa':return array('gigots');
case'giiaia':return array('gilets','griefs');
case'giiaaa':return array('gilets','glisse','grises');
case'giiiaa':return array('gilles');
case'giioia':return array('girafe');
case'giiaii':return array('giron');
case'giioii':return array('gitan');
case'giaoii':return array('gitan');
case'gioiaa':return array('glaise','gratis','gratos');
case'gioaaa':return array('glaise','graces','grades','grasse','gratis','gratos');
case'gioiba':return array('glaive');
case'gioaba':return array('glaive');
case'giopii':return array('glapir');
case'giopai':return array('glapir');
case'giaaaa':return array('glisse','grises','grosse','grosso','grotte');
case'giaaoi':return array('global');
case'giaiia':return array('gloire','greffe','grene','grenu','griffe','grille','grotte');
case'giaaia':return array('gloire','griefs','grotte');
case'giooaa':return array('grades');
case'gioiii':return array('grain','grant');
case'gioaii':return array('grain');
case'gioiia':return array('grand','grant','gratis');
case'gioiio':return array('grand');
case'gioppa':return array('grappe');
case'gioaia':return array('gratis');
case'giobai':return array('graver','gravir');
case'giobaa':return array('graves');
case'giobii':return array('gravir');
case'giaaii':return array('green');
case'giaiio':return array('grenu');
case'giabaa':return array('greves');
case'giiiia':return array('griffe','grille');
case'giippa':return array('grippe');
case'giappa':return array('grippe');
case'giiaai':return array('griser');
case'giaiaa':return array('grotte');
case'giaapa':return array('groupe');
case'giaopa':return array('groupe');
default: return array();}}
?>