<?php
function gwc_coupable_bas_min_6_go($code){switch($code){
case'goaaii':return array('gabon','gueux');
case'goagai':return array('gadget');
case'googai':return array('gadget');
case'goagaa':return array('gadget');
case'googaa':return array('gadget');
case'goaaaa':return array('gadoue','gaiete','guette','gueuse','guides');
case'gooaaa':return array('gadoue');
case'goaaoa':return array('gadoue','gateau');
case'gooaoa':return array('gadoue');
case'goaiia':return array('gaelle','gaine','gains','guelte','guerre','guette','yacht');
case'gogiia':return array('gagne');
case'goiaia':return array('gaiete','galere','galure');
case'goaaia':return array('gaiete','guette','gueule');
case'goiaaa':return array('gaiete','gardes','guides');
case'goiiia':return array('gaine','gains','gants');
case'goiiaa':return array('galles','ganse','gants','garros');
case'goioia':return array('galure');
case'goioga':return array('garage');
case'goiaio':return array('garcia');
case'goiaao':return array('garcia');
case'goiaai':return array('garder','guider');
case'goioai':return array('garder','guider');
case'goioaa':return array('gardes','guides');
case'goiaoa':return array('gateau');
case'goiaoo':return array('gateau');
case'goaaoo':return array('gateau');
case'gozaio':return array('gazera');
case'gozaia':return array('gazole');
case'gozaii':return array('gazon');
case'goaiaa':return array('guelte','guette');
case'goaiii':return array('guerir','yacht');
case'goaiai':return array('guerir');
case'goaoia':return array('gueule');
case'goaoaa':return array('gueuse','guides');
case'goaoii':return array('gueux');
case'goaaai':return array('guider','yasser');
case'goaoai':return array('guider');
default: return array();}}
?>