<?php
function gwc_coupable_haut_min_8_om($code){switch($code){
case'omoiooio':return array('amaigrir');
case'omoloomo':return array('amalgame');
case'omoodioo':return array('amandier');
case'omotoiio':return array('amateur');
case'omotoioo':return array('amatrice');
case'omhioooo':return array('ambiance');
case'omhiooto':return array('ambiante');
case'omhioiio':return array('ambigue');
case'omhitioo':return array('ambition');
case'omoliooo':return array('ameliore');
case'omoooooo':return array('amenagee','amenager','empresse');
case'ommooioo':return array('ammoniac');
case'omoiotio':return array('amnistie');
case'omohihio':return array('amphibie');
case'omoloiio':return array('ampleur','employe');
case'omooiilo':return array('ampoule');
case'omoiitoo':return array('amputer','emeutes');
case'omiiooot':return array('amusant');
case'omoilloo':return array('emailler');
case'omholloo':return array('emballer');
case'omhooooo':return array('embarras','embraser','embrasse');
case'omhollio':return array('embellie');
case'omhotoot':return array('embetant');
case'omhloiio':return array('emblave');
case'omhoiioo':return array('embryon');
case'omooooot':return array('emergent');
case'omiooooo':return array('eminence');
case'omiooioo':return array('emission','omission');
case'ommoodoo':return array('emmerder');
case'omotiooo':return array('emotions');
case'omoiiooo':return array('emousse');
case'omooohoo':return array('empecher');
case'omolotto':return array('emplette');
case'omoootoo':return array('emporter','emportes');
case'omoooiot':return array('empreint');
case'omooiiot':return array('emprunt');
case'omhoollo':return array('ombrelle');
case'omooloto':return array('omoplate');
default: return array();}}
?>