<?php
function gwc_centrale_10_MA($code){switch($code){
case'MABBAABAIB':return array('maconnerie');
case'MABBAAIQUB':return array('maconnique');
case'MABHABBIAB':return array('maghrebine','maghrebins');
case'MABIBTAATB':return array('magistrats');
case'MABABTIQUB':return array('magnetique');
case'MABAIFIQUB':return array('magnifique');
case'MAIATBAAIT':return array('maintenait');
case'MAIATBAAAT':return array('maintenant');
case'MAJBBTUBUH':return array('majestueux');
case'MAJBAATIBA':return array('majoration');
case'MALABABBBB':return array('maladresse');
case'MALABABITB':return array('maladroite');
case'MALBATBABU':return array('malentendu');
case'MALFAITBUA':return array('malfaiteur');
case'MALBABTBUT':return array('malgretout');
case'MALHBUABUH':return array('malheureux');
case'MALHBAABTB':return array('malhonnete');
case'MAAABBMBAT':return array('management');
case'MAABHBBTBA':return array('manchester');
case'MAABATAIAB':return array('mandataire');
case'MAAIFBBTBB':return array('manifestee');
case'MAAIFBBTBA':return array('manifester');
case'MAAIBAABBA':return array('manigancer');
case'MAAABQUIAB':return array('mannequins');
case'MAABBUVABB':return array('manoeuvres');
case'MAAQUAIBAT':return array('manquaient');
case'MAAQUBABAT':return array('manqueront');
case'MAAUBBAITB':return array('manuscrits');
case'MAQUILLABB':return array('maquillage');
case'MAQUIBAABB':return array('maquisards');
case'MAABHBPIBB':return array('marchepied');
case'MAABUBAITB':return array('marguerite');
case'MAABBAIABB':return array('marocaines');
case'MAAABAAIBA':return array('marronnier');
case'MAATIAIQUB':return array('martinique');
case'MAATYAIBBA':return array('martyriser');
case'MABTBBBATB':return array('mastodonte');
case'MATBHFIAAL':return array('matchfinal');
case'MATBAIBLLB':return array('materielle');
case'MATBAABLLB':return array('maternelle');
case'MAUAITAAIB':return array('mauritanie');
case'MAHILLAIAB':return array('maxillaire');
default: return array();}}
?>