<?php
function gwc_coupable_haut_min_7_mi($code){switch($code){
case'miohool':return array('michael');
case'mioholo':return array('michele');
case'miohoii':return array('mickey');
case'mioooho':return array('microbe');
case'miooooo':return array('miennes');
case'miottoo':return array('miettes');
case'mioiiii':return array('mieux');
case'miooood':return array('mignard');
case'miiiodo':return array('mikado');
case'miliooo':return array('milices');
case'milioii':return array('milieu');
case'militoo':return array('militer');
case'milloii':return array('millau');
case'millioo':return array('millier','million');
case'mioohlo':return array('minable');
case'miooooi':return array('minerai');
case'miooiio':return array('mineur');
case'mioiooo':return array('miniere');
case'mioimol':return array('minimal');
case'mioitol':return array('minitel');
case'mioiiit':return array('minuit');
case'mioiito':return array('minute');
case'mioohoo':return array('mioches');
case'miooolo':return array('miracle');
case'miooioo':return array('miroirs','mission');
case'miooilo':return array('missile');
case'miotool':return array('mistral');
case'mitoioo':return array('mitaine');
case'mitomoo':return array('mitemps');
case'miiitoo':return array('mixtes');
case'miiotto':return array('muette');
case'miilloo':return array('muller');
case'miioioh':return array('munich');
case'miioiol':return array('muriel');
case'miioolo':return array('muscle');
case'miioooo':return array('musees');
case'miiooot':return array('musset');
case'miitilo':return array('mutile');
case'miiooio':return array('myopie');
case'miioiom':return array('myriam');
case'miithoo':return array('mythes');
default: return array();}}
?>