<?php
function gwc_coupable_haut_min_7_ot($code){switch($code){
case'otolioo':return array('atelier','staline');
case'othoooo':return array('athenes');
case'othloto':return array('athlete');
case'otlooto':return array('atlanta');
case'otoiito':return array('atouts');
case'ottooho':return array('attache');
case'ottoodo':return array('attarde');
case'ottoiot':return array('atteint');
case'ottoloo':return array('atteler');
case'ottooto':return array('attente');
case'ottifoo':return array('attifer');
case'ottiooo':return array('attirer','attires','attiser');
case'ottooit':return array('attrait');
case'otohlio':return array('etablie','etablir','etablis');
case'otohlit':return array('etablit');
case'otooooo':return array('etagere','etonner','etonnes','etrange','etrenne','stopper');
case'otoioot':return array('etaient');
case'otolooo':return array('etalage');
case'otomooo':return array('etamage');
case'otoooho':return array('etanche');
case'otoiioo':return array('etayer');
case'otoodoo':return array('etendre');
case'otoodii':return array('etendu');
case'otooool':return array('eternel');
case'otioooo':return array('etienne');
case'otoiloo':return array('etoiles');
case'otoillo':return array('etrille');
case'otooito':return array('etroite','etroits');
case'otiidoo':return array('etudes');
case'otiidio':return array('etudie','studio');
case'ottomoo':return array('ottoman');
case'otohloo':return array('stables');
case'ototioo':return array('station');
case'ototiio':return array('statue');
case'ototiit':return array('statut');
case'otooolo':return array('steeple');
case'otoohoo':return array('stephan','stephen','stocker');
case'otooilo':return array('sterile');
case'otooiio':return array('stocks');
case'otoioto':return array('stricte');
case'otiiloo':return array('styles');
default: return array();}}
?>