<?php
function gwc_centrale_4_BB($code){switch($code){
case'BBAU':return array('beau','seau');
case'BBBB':return array('bebe','boss','cede','code','dodo','dose','gogo','secs');
case'BBBA':return array('been','beer','coca','deca','eden','egon','egor','oser');
case'BBLL':return array('bell');
case'BBAZ':return array('benz');
case'BBBT':return array('best','ecot');
case'BBTA':return array('beta');
case'BBTB':return array('bete','cote','dote','este','sets');
case'BBBH':return array('bock');
case'BBIB':return array('bois','dois','scie','soie');
case'BBAB':return array('bond','bons','bord','cons','donc','dons','dore','gene','gens','gere','gers','ogre','sens','sons');
case'BBAA':return array('bonn','cora','sera');
case'BBBM':return array('boom');
case'BBUB':return array('bouc','boue','deug','doue','ecus','obus','sous');
case'BBUM':return array('boum');
case'BBUT':return array('bout','cout','gout');
case'BBHB':return array('boxe','echo');
case'BBYB':return array('boys');
case'BBBI':return array('ceci');
case'BBLA':return array('cela','cola');
case'BBAT':return array('cent','dent','dont','dort','sent','sert','sont','sort');
case'BBAF':return array('cerf','serf');
case'BBUH':return array('ceux','deux','doux');
case'BBIA':return array('coin','sein','soin','soir');
case'BBLB':return array('cols','dole','gele','oslo','solo','sols');
case'BBMA':return array('coma');
case'BBUP':return array('coup');
case'BBUA':return array('cour');
case'BBBU':return array('decu');
case'BBFI':return array('defi');
case'BBJA':return array('deja');
case'BBMI':return array('demi','semi');
case'BBIT':return array('doit','edit','soit');
case'BBMB':return array('dome','seme');
case'BBAL':return array('egal');
case'BBLF':return array('golf');
case'BBIL':return array('oeil');
case'BBUF':return array('oeuf');
case'BBPT':return array('sept');
case'BBUL':return array('seul','soul');
case'BBVB':return array('seve');
case'BBIF':return array('soif');
case'BBAY':return array('sony');
default: return array();}}
?>