<?php
function gwc_coupable_bas_min_7_bi($code){switch($code){
case'bioiiaa':return array('viande');
case'bioiioa':return array('viande');
case'biaoiia':return array('vicaire','visant');
case'biaoaia':return array('vicaire');
case'biaiiia':return array('vieille','vieilli');
case'biaaiia':return array('vieille','vieilli','visent');
case'biaiiii':return array('vieilli');
case'biaaiii':return array('vieilli','visent');
case'biaigaa':return array('vierges');
case'bigaaai':return array('vigueur');
case'bigoaai':return array('vigueur');
case'bigaaoi':return array('vigueur');
case'bigoaoi':return array('vigueur');
case'biiiiai':return array('viktor');
case'biiiaai':return array('viktor');
case'biioiii':return array('vilain');
case'biioaii':return array('vilain');
case'biiioga':return array('village');
case'biaiaii':return array('violon','vision');
case'biiaiii':return array('virent');
case'biiaiia':return array('virent');
case'biigiii':return array('virgin');
case'biigaii':return array('virgin');
case'biigaia':return array('virgule');
case'biigoia':return array('virgule');
case'biaogaa':return array('visages');
case'biaoiii':return array('visant');
case'biaiaia':return array('visible');
case'biaaaia':return array('visible');
case'biaaaii':return array('vision');
case'biaiiai':return array('visiter');
case'biaaiai':return array('visiter');
case'biaiaai':return array('visiter');
case'biaaaai':return array('visiter');
case'biaiiaa':return array('visites');
case'biaaiaa':return array('visites');
case'biaiaaa':return array('visites');
case'biaaaaa':return array('visites','vitesse');
case'biiaaaa':return array('vitesse');
case'biboiii':return array('vivant');
case'biboiia':return array('vivant');
case'bibaiii':return array('vivent');
case'bibaiia':return array('vivent','vivons');
case'bibiaii':return array('vivien');
case'bibaaii':return array('vivien');
default: return array();}}
?>