<?php
function gwc_coupable_bas_min_9_ab($code){switch($code){
case'aboaaoiii':return array('evacuant');
case'aboaooiii':return array('evacuant');
case'aboaaoiia':return array('evacuant');
case'aboaooiia':return array('evacuant');
case'aboiaaiii':return array('evaluent');
case'aboioaiii':return array('evaluent');
case'aboiaaiia':return array('evaluent');
case'aboioaiia':return array('evaluent');
case'aboiigiia':return array('evangile');
case'aboiigaia':return array('evangile');
case'abaiiioii':return array('eventail');
case'abaiiaoii':return array('eventail');
case'abaiiioai':return array('eventail','eventuel');
case'abaiiaoai':return array('eventail','eventuel');
case'abaiiiaai':return array('eventuel');
case'abaiiaaai':return array('eventuel');
case'abiaaiiaa':return array('evidence','evidente');
case'abaaaiiaa':return array('evidence','evidente');
case'abioaiiaa':return array('evidence','evidente');
case'abaoaiiaa':return array('evidence','evidente');
case'abiaaiiia':return array('evidente');
case'abaaaiiia':return array('evidente');
case'abioaiiia':return array('evidente');
case'abaoaiiia':return array('evidente');
case'abaiaaiii':return array('evoluent');
case'abaioaiii':return array('evoluent');
case'abaiaaiia':return array('evoluent');
case'abaioaiia':return array('evoluent');
case'abaqaoiii':return array('evoquant');
case'abaqooiii':return array('evoquant');
case'abaqaoiia':return array('evoquant');
case'abaqooiia':return array('evoquant');
case'abaqaaiii':return array('evoquent');
case'abaqoaiii':return array('evoquent');
case'abaqaaiia':return array('evoquent');
case'abaqoaiia':return array('evoquent');
default: return array();}}
?>