<?php
function gwc_coupable_bas_min_8_ag($code){switch($code){
case'agaiiaia':return array('cycliste','egotiste');
case'agaiaaia':return array('cycliste','egotiste');
case'agaiiaaa':return array('cycliste','egotiste');
case'agaiaaaa':return array('cycliste','egotiste');
case'agaiaiia':return array('cyclone');
case'agiiiqaa':return array('cynique');
case'agiiaqaa':return array('cynique');
case'agiiiqoa':return array('cynique');
case'agiiaqoa':return array('cynique');
case'agoiiaai':return array('egaliser');
case'agoiaaai':return array('egaliser');
case'agaiiqaa':return array('egotique');
case'agaaiqaa':return array('egotique');
case'agaiaqaa':return array('egotique');
case'agaaaqaa':return array('egotique');
case'agaiiqoa':return array('egotique');
case'agaaiqoa':return array('egotique');
case'agaiaqoa':return array('egotique');
case'agaaaqoa':return array('egotique');
case'agaaiaia':return array('egotiste');
case'agaaaaia':return array('egotiste');
case'agaaiaaa':return array('egotiste');
case'agaaaaaa':return array('egotiste');
case'agaaiiai':return array('egoutter');
case'agaoiiai':return array('egoutter');
case'agaaaiai':return array('egoutter');
case'agaoaiai':return array('egoutter');
case'agaaiaai':return array('egoutter');
case'agaoiaai':return array('egoutter');
case'agaaaaai':return array('egoutter');
case'agaoaaai':return array('egoutter');
case'agiiaaia':return array('ignoble');
case'agiiaiai':return array('ignorer');
case'agiboiii':return array('sylvain');
case'agiboaii':return array('sylvain');
case'agiiaiia':return array('syriens');
case'agiaaiia':return array('syriens');
case'agpiiaii':return array('typhon');
default: return array();}}
?>