<?php
function gwc_coupable_bas_min_23_ai($code){switch($code){
case'aiiiiiioiiqaoaiaiiiaiii':return array('immanquablement');
case'aiiiiiioiiqooaiaiiiaiii':return array('immanquablement');
case'aiiiiiioiiqaoaiaiiiaiia':return array('immanquablement');
case'aiiiiiioiiqooaiaiiiaiia':return array('immanquablement');
case'aioaiiiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aiooiiiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aioaaiiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aiooaiiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aioaiaiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aiooiaiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aioaaaiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aiooaaiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aioaiiaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aiooiiaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aioaaiaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aiooaiaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aioaiaaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aiooiaaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aioaaaaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aiooaaaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'aioaiiiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aiooiiiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aioaaiiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aiooaiiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aioaiaiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aiooiaiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aioaaaiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aiooaaiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aioaiiaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aiooiiaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aioaaiaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aiooaiaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aioaiaaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aiooiaaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aioaaaaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aiooaaaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'aiaiiiaiaiiiaiiiaaiaiia':return array('tremblementdeterre');
case'aiaiiiaiaiiiaiiaaaiaiia':return array('tremblementdeterre');
case'aiaiiiaiaiiiaiiioaiaiia':return array('tremblementdeterre');
case'aiaiiiaiaiiiaiiaoaiaiia':return array('tremblementdeterre');
case'aiaiiiaiaiiiaiiiaaaaiia':return array('tremblementdeterre');
case'aiaiiiaiaiiiaiiaaaaaiia':return array('tremblementdeterre');
case'aiaiiiaiaiiiaiiioaaaiia':return array('tremblementdeterre');
case'aiaiiiaiaiiiaiiaoaaaiia':return array('tremblementdeterre');
default: return array();}}
?>