<?php
function gwc_coupable_bas_min_23_ii($code){switch($code){
case'iiiiiiioiiqaoaiaiiiaiii':return array('immanquablement');
case'iiiiiiioiiqooaiaiiiaiii':return array('immanquablement');
case'iiiiiiioiiqaoaiaiiiaiia':return array('immanquablement');
case'iiiiiiioiiqooaiaiiiaiia':return array('immanquablement');
case'iioaiiiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iiooiiiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iioaaiiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iiooaiiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iioaiaiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iiooiaiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iioaaaiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iiooaaiaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iioaiiaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iiooiiaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iioaaiaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iiooaiaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iioaiaaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iiooiaaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iioaaaaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iiooaaaaiiiiaiiaiiiaiii':return array('traditionnellement');
case'iioaiiiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iiooiiiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iioaaiiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iiooaiiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iioaiaiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iiooiaiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iioaaaiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iiooaaiaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iioaiiaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iiooiiaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iioaaiaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iiooaiaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iioaiaaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iiooiaaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iioaaaaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iiooaaaaiiiiaiiaiiiaiia':return array('traditionnellement');
case'iiaiiiaiaiiiaiiiaaiaiia':return array('tremblementdeterre');
case'iiaiiiaiaiiiaiiaaaiaiia':return array('tremblementdeterre');
case'iiaiiiaiaiiiaiiioaiaiia':return array('tremblementdeterre');
case'iiaiiiaiaiiiaiiaoaiaiia':return array('tremblementdeterre');
case'iiaiiiaiaiiiaiiiaaaaiia':return array('tremblementdeterre');
case'iiaiiiaiaiiiaiiaaaaaiia':return array('tremblementdeterre');
case'iiaiiiaiaiiiaiiioaaaiia':return array('tremblementdeterre');
case'iiaiiiaiaiiiaiiaoaaaiia':return array('tremblementdeterre');
default: return array();}}
?>