<?php
function gwc_coupable_bas_min_18_ap($code){switch($code){
case'apoiiaaiaaaiiiaiii':return array('epanouissement');
case'apoiiaoiaaaiiiaiii':return array('epanouissement');
case'apoiiaaaaaaiiiaiii':return array('epanouissement');
case'apoiiaoaaaaiiiaiii':return array('epanouissement');
case'apoiiaaiaaaiiiaiia':return array('epanouissement');
case'apoiiaoiaaaiiiaiia':return array('epanouissement');
case'apoiiaaaaaaiiiaiia':return array('epanouissement');
case'apoiiaoaaaaiiiaiia':return array('epanouissement');
case'apiiiiaaiiaiiiaiii':return array('spirituellement');
case'apaiiiaaiiaiiiaiii':return array('spirituellement');
case'apiiaiaaiiaiiiaiii':return array('spirituellement');
case'apaiaiaaiiaiiiaiii':return array('spirituellement');
case'apiiiaaaiiaiiiaiii':return array('spirituellement');
case'apaiiaaaiiaiiiaiii':return array('spirituellement');
case'apiiaaaaiiaiiiaiii':return array('spirituellement');
case'apaiaaaaiiaiiiaiii':return array('spirituellement');
case'apiiiioaiiaiiiaiii':return array('spirituellement');
case'apaiiioaiiaiiiaiii':return array('spirituellement');
case'apiiaioaiiaiiiaiii':return array('spirituellement');
case'apaiaioaiiaiiiaiii':return array('spirituellement');
case'apiiiaoaiiaiiiaiii':return array('spirituellement');
case'apaiiaoaiiaiiiaiii':return array('spirituellement');
case'apiiaaoaiiaiiiaiii':return array('spirituellement');
case'apaiaaoaiiaiiiaiii':return array('spirituellement');
case'apiiiiaaiiaiiiaiia':return array('spirituellement');
case'apaiiiaaiiaiiiaiia':return array('spirituellement');
case'apiiaiaaiiaiiiaiia':return array('spirituellement');
case'apaiaiaaiiaiiiaiia':return array('spirituellement');
case'apiiiaaaiiaiiiaiia':return array('spirituellement');
case'apaiiaaaiiaiiiaiia':return array('spirituellement');
case'apiiaaaaiiaiiiaiia':return array('spirituellement');
case'apaiaaaaiiaiiiaiia':return array('spirituellement');
case'apiiiioaiiaiiiaiia':return array('spirituellement');
case'apaiiioaiiaiiiaiia':return array('spirituellement');
case'apiiaioaiiaiiiaiia':return array('spirituellement');
case'apaiaioaiiaiiiaiia':return array('spirituellement');
case'apiiiaoaiiaiiiaiia':return array('spirituellement');
case'apaiiaoaiiaiiiaiia':return array('spirituellement');
case'apiiaaoaiiaiiiaiia':return array('spirituellement');
case'apaiaaoaiiaiiiaiia':return array('spirituellement');
default: return array();}}
?>