<?php
function gwc_coupable_haut_min_12_ii($code){switch($code){
case'iiidioioiooo':return array('judiciaires');
case'iiidioioiiii':return array('judicieux');
case'iiioidiotioo':return array('juridiction');
case'iiioidioiioo':return array('juridiques');
case'iiiotioiohlo':return array('justiciable');
case'iiofiioioooo':return array('kafkaienne');
case'iihooioioooo':return array('ukrainienne');
case'iiiiooioiooo':return array('ukrainiens');
case'iiltooioiioo':return array('ulterieure');
case'iioooimomoot':return array('unanimement');
case'iioifiootioo':return array('unification');
case'iioilotooolo':return array('unilaterale');
case'iioioiiomoot':return array('uniquement');
case'iioiiioooito':return array('universite');
case'iitiliootioo':return array('utilisation');
case'iioillommoot':return array('vaillamment');
case'iioiooiioiio':return array('vainqueur');
case'iiooiohilito':return array('variabilite');
case'iiooooiiillo':return array('verrouille');
case'iiooootilito':return array('versatilite');
case'iiotooiooioo':return array('veterinaire');
case'iiotilloiiii':return array('vetilleux');
case'iiioooomooio':return array('viergemarie');
case'iiiotoomiooo':return array('vietnamiens');
case'iiillooooioo':return array('villageoise');
case'iiioloooollo':return array('violoncelle');
case'iiiotiiooito':return array('virtuosite');
case'iiioihlomoot':return array('visiblement');
case'iiioiooooioo':return array('visionnaire');
case'iiiooiioiiii':return array('visqueux');
case'iiolootoiooo':return array('volontaires');
case'iioiidooioot':return array('voudraient');
case'iioiioooiioo':return array('voyageurs','voyageuse');
case'iioooitziiii':return array('vranitzky');
case'iiiiloooohlo':return array('vulnerable');
case'iiioohiootoo':return array('washington');
default: return array();}}
?>