<?php
function gwc_coupable_haut_min_12_mo($code){switch($code){
case'modomoioollo':return array('mademoiselle');
case'mooioiiomoot':return array('magiquement');
case'moooifiooooo':return array('magnificence');
case'moooifioiioo':return array('magnifiques');
case'moiotiooooot':return array('maintiennent');
case'moiooitoiooo':return array('majoritaires');
case'molootoodoot':return array('malentendant');
case'molootoodiio':return array('malentendus');
case'molfoitoiioo':return array('malfaiteurs');
case'mollooooiooo':return array('mallearriere');
case'moliioilloot':return array('malveillant');
case'mooifootooto':return array('manifestants');
case'mooooiiiiooo':return array('manoeuvres');
case'moooioooloot':return array('maraissalant');
case'mooohoodiooo':return array('marchandises');
case'mooioooottoo':return array('marionnettes');
case'mooooilloioo':return array('marseillaise');
case'moooiilioito':return array('masculinite');
case'moooiiiomoot':return array('massivement');
case'modiotioiioo':return array('mediatiques');
case'modioolomoot':return array('medicalement');
case'moditooooooo':return array('mediterranee');
case'momooiootioo':return array('memorisation');
case'moooiiioooio':return array('mesquinerie');
case'motollioiioo':return array('metalliques');
case'motolliiooio':return array('metallurgie');
case'motomooohooo':return array('metamorphose');
case'motoooolooio':return array('meteorologie');
case'mothodolooio':return array('methodologie');
case'mohiliootioo':return array('mobilisation');
case'modifiootioo':return array('modification');
case'moiooooooiio':return array('moissonneur');
case'molooiiloioo':return array('moleculaire');
case'mooooohioiio':return array('monarchique');
case'mootooooiiii':return array('montagneux');
case'mootolomhoot':return array('montalembert');
case'mootoooooooo':return array('montparnasse');
case'mooiimootolo':return array('monumentale');
case'moooliootioo':return array('moralisation');
case'mooohioomooo':return array('morphinomane');
case'motiiiotiooo':return array('motivations');
case'moiidiohidio':return array('moudjahidin');
case'moiiiiomooto':return array('mouvemente','mouvements');
default: return array();}}
?>