<?php
function gwc_coupable_haut_maj_19_MA($code){switch($code){
case'MAIIIAIIAAIIAAMAIIT':return array('malheureusement');
case'MAIIICIIAAIIAAMAIIT':return array('malheureusement');
case'MAIIIAIIACIIAAMAIIT':return array('malheureusement');
case'MAIIICIIACIIAAMAIIT':return array('malheureusement');
case'MAIIIAIIAAIICAMAIIT':return array('malheureusement');
case'MAIIICIIAAIICAMAIIT':return array('malheureusement');
case'MAIIIAIIACIICAMAIIT':return array('malheureusement');
case'MAIIICIIACIICAMAIIT':return array('malheureusement');
case'MAIIIAIIAAIIACMAIIT':return array('malheureusement');
case'MAIIICIIAAIIACMAIIT':return array('malheureusement');
case'MAIIIAIIACIIACMAIIT':return array('malheureusement');
case'MAIIICIIACIIACMAIIT':return array('malheureusement');
case'MAIIIAIIAAIICCMAIIT':return array('malheureusement');
case'MAIIICIIAAIICCMAIIT':return array('malheureusement');
case'MAIIIAIIACIICCMAIIT':return array('malheureusement');
case'MAIIICIIACIICCMAIIT':return array('malheureusement');
case'MAIIIAIIAAIIAAMCIIT':return array('malheureusement');
case'MAIIICIIAAIIAAMCIIT':return array('malheureusement');
case'MAIIIAIIACIIAAMCIIT':return array('malheureusement');
case'MAIIICIIACIIAAMCIIT':return array('malheureusement');
case'MAIIIAIIAAIICAMCIIT':return array('malheureusement');
case'MAIIICIIAAIICAMCIIT':return array('malheureusement');
case'MAIIIAIIACIICAMCIIT':return array('malheureusement');
case'MAIIICIIACIICAMCIIT':return array('malheureusement');
case'MAIIIAIIAAIIACMCIIT':return array('malheureusement');
case'MAIIICIIAAIIACMCIIT':return array('malheureusement');
case'MAIIIAIIACIIACMCIIT':return array('malheureusement');
case'MAIIICIIACIIACMCIIT':return array('malheureusement');
case'MAIIIAIIAAIICCMCIIT':return array('malheureusement');
case'MAIIICIIAAIICCMCIIT':return array('malheureusement');
case'MAIIIAIIACIICCMCIIT':return array('malheureusement');
case'MAIIICIIACIICCMCIIT':return array('malheureusement');
case'MAIAIIAAIIAIIAMAIIT':return array('melancoliquement');
case'MAIAIICAIIAIIAMAIIT':return array('melancoliquement');
case'MAIAIIAAIIAIICMAIIT':return array('melancoliquement');
case'MAIAIICAIIAIICMAIIT':return array('melancoliquement');
case'MAIAIIAAIIAIIAMCIIT':return array('melancoliquement');
case'MAIAIICAIIAIIAMCIIT':return array('melancoliquement');
case'MAIAIIAAIIAIICMCIIT':return array('melancoliquement');
case'MAIAIICAIIAIICMCIIT':return array('melancoliquement');
case'MATAAIIAAIAIIAMAIIT':return array('metaphoriquement');
case'MATAAIIAAIAIICMAIIT':return array('metaphoriquement');
case'MATAAIIAAIAIIAMCIIT':return array('metaphoriquement');
case'MATAAIIAAIAIICMCIIT':return array('metaphoriquement');
default: return array();}}
?>