<?php
function gwc_centrale_8_AU($code){switch($code){
case'AUABBIMB':return array('auregime');
case'AUBBHBAB':return array('audehors');
case'AUBBBBUB':return array('audessus');
case'AUBBVAAT':return array('audevant');
case'AUBIBABB':return array('audience');
case'AUBITBUA':return array('auditeur');
case'AUBITIBA':return array('audition');
case'AUBMBATB':return array('augmente');
case'AUMBAIBA':return array('aumonier');
case'AUPABBBB':return array('aupresde');
case'AUAAIBAT':return array('auraient');
case'AUAIFBAB':return array('aurifere');
case'AUBPIBBB':return array('auspices');
case'AUBBITBT':return array('aussitot');
case'AUBTAALB':return array('australe');
case'AUBTAAUH':return array('austraux');
case'AUTBBAFB':return array('autodafe');
case'AUTBMATB':return array('automate');
case'AUTBMAAL':return array('automnal');
case'AUTBABMB':return array('autonome');
case'AUTBPBIB':return array('autopsie');
case'AUTBAIBB':return array('autorise');
case'AUTBAITB':return array('autorite');
case'AUTBBTBP':return array('autostop');
case'AUTAIBHB':return array('autriche');
case'AUTAUBHB':return array('autruche');
case'AUHQUBLB':return array('auxquels');
case'AUIBAABB':return array('nuisance');
case'AUIBIBLB':return array('nuisible');
case'AUTAITIF':return array('nutritif');
case'AUBIBBAB':return array('rubicond');
case'AUBAIQUB':return array('rubrique');
case'AUBBBITB':return array('rugosite');
case'AUIBBBAU':return array('ruisseau');
case'AUBTIQUB':return array('rustique');
case'AUTABABA':return array('rutabaga');
case'AUTILAAT':return array('rutilant');
default: return array();}}
?>