<?php
function gwc_centrale_8_BL($code){switch($code){
case'BLAIABAU':return array('blaireau');
case'BLAABHBB':return array('blanches');
case'BLAABHIA':return array('blanchir');
case'BLBBBAAT':return array('blessant');
case'BLBBBBBB':return array('blessees');
case'BLBBBUAB':return array('blessure');
case'BLBBABBB':return array('blocages');
case'BLBQUBBB':return array('bloquees');
case'BLBQUBAT':return array('bloquent');
case'BLUFFBUA':return array('bluffeur');
case'BLAPBTBA':return array('clapoter');
case'BLAAIFIB':return array('clarifie');
case'BLAVIBAB':return array('claviers');
case'BLBMBABB':return array('clemence');
case'BLBAMBAT':return array('clermont');
case'BLIBATBB':return array('clientes');
case'BLIAIQUB':return array('clinique');
case'BLIVABBB':return array('clivages');
case'BLBBHAAB':return array('clochard');
case'BLBITABA':return array('cloitrer');
case'BLBTUABA':return array('cloturer');
case'BLABBABB':return array('elaboree','elabores');
case'BLABBABA':return array('elaborer');
case'BLBBTBUA':return array('electeur');
case'BLBBTIBA':return array('election');
case'BLBBAABB':return array('elegance');
case'BLBBAATB':return array('elegante');
case'BLBMBATB':return array('elements');
case'BLBPHAAT':return array('elephant');
case'BLBVABBB':return array('elevages');
case'BLBVBUAB':return array('eleveurs');
case'BLIMIABA':return array('eliminer');
case'BLITAIAB':return array('elitaire');
case'BLITIBTB':return array('elitiste');
case'BLBIBABB':return array('eloignee','eloignes');
case'BLBIBABA':return array('eloigner');
case'BLUBIBBA':return array('elucider');
case'BLABIBAB':return array('glaciere');
case'BLAAUABB':return array('glanures');
case'BLABABBT':return array('glasnost');
case'BLIBBBAT':return array('glissent');
case'BLBBALBB':return array('globales');
case'BLBAIBUH':return array('glorieux');
case'BLBVBABB':return array('slovenes');
case'BLBVBAIB':return array('slovenie');
default: return array();}}
?>