<?php
function gwc_centrale_8_BP($code){switch($code){
case'BPAABABB':return array('epargnee');
case'BPAABABA':return array('epargner');
case'BPBAVIBA':return array('epervier');
case'BPHBMBAB':return array('ephemere');
case'BPIBBAIB':return array('epicerie');
case'BPIBBMIB':return array('epidemie');
case'BPIBBAMB':return array('epiderme');
case'BPIABLBA':return array('epingler');
case'BPIBBBBB':return array('episodes');
case'BPLUBHBA':return array('eplucher');
case'BPABABAB':return array('eprendre');
case'BPABUVBB':return array('epreuves');
case'BPABUVBA':return array('eprouver');
case'BPIAIBAB':return array('opinions');
case'BPIBMAAB':return array('opiomane');
case'BPPBATUA':return array('opportun');
case'BPPBBAIT':return array('opposait');
case'BPPBBAAT':return array('opposant');
case'BPPBBBBB':return array('opposees');
case'BPPBBBAT':return array('opposent');
case'BPPAIMBA':return array('opprimer');
case'BPPABBAB':return array('opprobre');
case'BPTIQUBB':return array('optiques');
case'BPULBABB':return array('opulence');
case'BPABIBUH':return array('spacieux');
case'BPATIALB':return array('spatiale');
case'BPBBIALB':return array('speciale');
case'BPBBIAUH':return array('speciaux');
case'BPBBIBUH':return array('specieux');
case'BPBBIFIB':return array('specifie');
case'BPBBIMBA':return array('specimen');
case'BPBATAAB':return array('spontane');
case'BPBATIFB':return array('sportifs');
case'BPBATIVB':return array('sportive');
case'BPBUTAIH':return array('spoutnik');
default: return array();}}
?>