<?php
function gwc_centrale_8_FB($code){switch($code){
case'FBBBABBA':return array('feconder');
case'FBBBAALB':return array('federale');
case'FBBBAAUH':return array('federaux');
case'FBBAIQUB':return array('feerique');
case'FBLIBITB':return array('felicite');
case'FBMIAIAB':return array('feminine','feminins');
case'FBAAIBAT':return array('feraient');
case'FBAAAABB':return array('fernando');
case'FBABBITB':return array('ferocite');
case'FBBTIVAL':return array('festival');
case'FBBTBYBA':return array('festoyer');
case'FBUILLBB':return array('feuilles','fouilles');
case'FBLHLBAB':return array('folklore');
case'FBMBATBA':return array('fomenter');
case'FBABIBAB':return array('fonciere','fonciers');
case'FBABTIBA':return array('fonction');
case'FBATAIAB':return array('fontaine');
case'FBATBAAY':return array('fontenay');
case'FBBTBALL':return array('football');
case'FBABBAIB':return array('forcerie');
case'FBABBABA':return array('forgeron');
case'FBAMBLLB':return array('formelle');
case'FBAMULBB':return array('formulee','formules');
case'FBAMULBA':return array('formuler');
case'FBATIBAI':return array('fortiori');
case'FBATUABB':return array('fortunes');
case'FBBBILBB':return array('fossiles');
case'FBUBAULT':return array('foucault');
case'FBUBTTBA':return array('fouetter');
case'FBUBUBUH':return array('fougueux');
case'FBUILLBA':return array('fouiller');
case'FBUIABUA':return array('fouineur');
case'FBULAABB':return array('foulards');
case'FBUABUBA':return array('fourguer');
case'FBUAABAU':return array('fourneau');
case'FBUAAIBA':return array('fournier','fourrier');
case'FBUAAIBB':return array('fournies');
case'FBUAAIAA':return array('fournira');
case'FBUAAABB':return array('fourrage');
case'FBUAAUAB':return array('fourrure');
default: return array();}}
?>