<?php
function gwc_centrale_8_VB($code){switch($code){
case'VBBBTTBB':return array('vedettes');
case'VBHIBULB':return array('vehicule');
case'VBILLBAT':return array('veillent');
case'VBLBBITB':return array('velocite');
case'VBAAIBAT':return array('venaient');
case'VBABAABB':return array('vendange');
case'VBABBTTA':return array('vendetta');
case'VBABBUAB':return array('vendeurs');
case'VBABABBI':return array('vendredi');
case'VBABABUH':return array('veneneux');
case'VBAIMBUH':return array('venimeux');
case'VBATAUBB':return array('ventrues');
case'VBABLABB':return array('verglace');
case'VBAIFIBA':return array('verifier');
case'VBABIBAB':return array('versions');
case'VBATBBAB':return array('vertebre');
case'VBATIBAL':return array('vertical');
case'VBBIBULB':return array('vesicule');
case'VBBTIBBB':return array('vestiges');
case'VBTBMBAT':return array('vetement');
case'VBTBAAAB':return array('veterans');
case'VBTILLBA':return array('vetiller');
case'VBHATIBA':return array('vexation');
case'VBBATIBA':return array('vocation');
case'VBIBIABB':return array('voisines');
case'VBITUABA':return array('voiturer');
case'VBITUABB':return array('voitures');
case'VBLAILLB':return array('volaille');
case'VBLBATBB':return array('volontes');
case'VBLTAIAB':return array('voltaire');
case'VBLUBILB':return array('volubile');
case'VBUBAAIB':return array('voudrais');
case'VBUBAAIT':return array('voudrait');
case'VBYABBUA':return array('voyageur');
case'VBYAIBAT':return array('voyaient');
default: return array();}}
?>