<?php
function gwc_coupable_bas_maj_12_LL($code){switch($code){
case'LLIIIIOIIOII':return array('ceinturon');
case'LLLLOLIIIIIL':return array('cellulaire');
case'LLIIIIIIIILO':return array('centaines','certaines');
case'LLIIIIIIILLO':return array('centrales');
case'LLIIIIIIIOII':return array('centraux');
case'LLIIIIIIOILO':return array('centristes');
case'LLILIIOIIIII':return array('cependant');
case'LLIILIILILII':return array('cerealier');
case'LLIIIIIIOIII':return array('certificat');
case'LLIIIIIILIII':return array('certificat','echappent');
case'LLIIOIIOOLII':return array('clabauder');
case'LLIIIIIIILII':return array('clarifier','eliminer');
case'LLIIOOIQOLII':return array('claudiquer');
case'LLLIIIIIOIII':return array('clermont','eclaircir','lecanium');
case'LLIIIIIIOLLO':return array('echangees');
case'LLIIIIIIOLII':return array('echanger');
case'LLIILIIIIOLO':return array('echeances');
case'LLIILIIIILLO':return array('echeances');
case'LLLIIIIIIIOL':return array('eclairage');
case'LLLIIIIILIII':return array('eclaircir');
case'LLLIIIIIIIIL':return array('eclatante');
case'LLOLOIIIIIII':return array('ecoeurant');
case'LLOIIOIIIILO':return array('economies');
case'LLIIIVIIIIIO':return array('ecrivains');
case'LLLOIOIIIILL':return array('electorale');
case'LLLLIOIIIILL':return array('electorale');
case'LLLOIIIIOIIL':return array('electricite');
case'LLLLIIIIOIIL':return array('electricite');
case'LLLOIIIILIIL':return array('electricite');
case'LLLLIIIILIIL':return array('electricite');
case'LLLOIIIIQOLO':return array('electriques');
case'LLLLIIIIQOLO':return array('electriques');
case'LLLIIIIIIIIO':return array('elephants');
case'LLOIIIIIOIII':return array('lecanium');
case'LLOIIIIIIIIL':return array('legataire','legitimite');
case'LLOIOLIIIIVL':return array('legislative');
case'LLOIIIIIILII':return array('legitimer');
case'LLIIIIIIIOIL':return array('lethargie');
default: return array();}}
?>