<?php
function gwc_coupable_bas_maj_17_OL($code){switch($code){
case'OLIIIIOOLOIIIIOII':return array('blancdechaux');
case'OLIIIILOLOIIIIOII':return array('blancdechaux');
case'OLIIIIOOLLIIIIOII':return array('blancdechaux');
case'OLIIIILOLLIIIIOII':return array('blancdechaux');
case'OLIIIIOIIIIIILIII':return array('blanchiment');
case'OLIIIILIIIIIILIII':return array('blanchiment');
case'OLIIIIOIIIOOLIIIL':return array('blanchisserie');
case'OLIIIILIIIOOLIIIL':return array('blanchisserie');
case'OLIIIIIIIOIIIIOII':return array('clarification','demarcation');
case'OLIIIIIIILIIIIOII':return array('clarification','demarcation');
case'OLIIOOIIIOIIIIOII':return array('classification');
case'OLIIOOIIILIIIIOII':return array('classification');
case'OLOIIIIQOLIIILIII':return array('debarquement');
case'OLOOLOIIIOIIIIOII':return array('decolonisation');
case'OLLOLOIIIOIIIIOII':return array('decolonisation');
case'OLLOOIILIOIIIIOII':return array('delocalisation');
case'OLLOLIILIOIIIIOII':return array('delocalisation');
case'OLIIIIIIIOIIILIII':return array('demandaient');
case'OLIIIIIIIOLIILOOL':return array('demanderesse');
case'OLIIIIOOIOIIIILII':return array('demissionner');
case'OLIIIOOIIIIIIQOLO':return array('democratiques');
case'OLIIIOLIIIIIIQOLO':return array('democratiques');
case'OLIIIOOIIIIIIOLII':return array('democratiser');
case'OLIIIOLIIIIIIOLII':return array('democratiser');
case'OLIIIOIIOIIIIIIII':return array('demonstratif');
case'OLIIIIIILIIILIIIO':return array('departements');
case'OLILIIIOOLIIILIII':return array('deperissement');
case'OLOIIIIIIOOVIIIII':return array('desapprouvant');
case'OLOLIIOIIIIIIILII':return array('desenchanter');
case'OLOLIILIIIIIIILII':return array('desenchanter');
case'OLOLOILIILIIILIII':return array('desesperement');
case'OLOILLOOIOIIIILII':return array('desillusionner');
case'OLILIIIOIIIIIIOII':return array('deterioration');
case'OLILIIIIIIIIIIIII':return array('determinant');
case'OLIOOIIIILIIILIII':return array('detournement');
case'OLVLLOIILIIILIIIO':return array('developpements');
case'OLVILIIOIIIIILIII':return array('deviendraient');
case'OLIIIIOOLIIILIIIO':return array('gemissements');
case'OLIIOIIIIIIILIIIL':return array('gendarmerie');
case'OLOIIOIIIIIIIIILO':return array('gestionnaires');
case'OLIIIIOOIIIIIIIIL':return array('scanographie');
case'OLIIIZOIIIIILIIIL':return array('schizophrenie');
case'OLIIIIIIILIIIIILL':return array('sentimentale');
case'OLIILIIIIIIOIIIIL':return array('septentrional');
default: return array();}}
?>