<?php
function gwc_coupable_haut_maj_23_AI($code){switch($code){
case'AIITIAAIIATITIITIAIIAAI':return array('anticonstitutionnel');
case'AIITICAIIATITIITIAIIAAI':return array('anticonstitutionnel');
case'AIITIAAIICTITIITIAIIAAI':return array('anticonstitutionnel');
case'AIITICAIICTITIITIAIIAAI':return array('anticonstitutionnel');
case'AIITIAAIIATITIITIAAIIAI':return array('anticonstitutionnel');
case'AIITICAIIATITIITIAAIIAI':return array('anticonstitutionnel');
case'AIITIAAIICTITIITIAAIIAI':return array('anticonstitutionnel');
case'AIITICAIICTITIITIAAIIAI':return array('anticonstitutionnel');
case'AIITIAAAATITIITIAIIIIAI':return array('anticonstitutionnel');
case'AIITICAAATITIITIAIIIIAI':return array('anticonstitutionnel');
case'AIITIAAACTITIITIAIIIIAI':return array('anticonstitutionnel');
case'AIITICAACTITIITIAIIIIAI':return array('anticonstitutionnel');
case'AIITIAAIIATITIITIAIIACI':return array('anticonstitutionnel');
case'AIITICAIIATITIITIAIIACI':return array('anticonstitutionnel');
case'AIITIAAIICTITIITIAIIACI':return array('anticonstitutionnel');
case'AIITICAIICTITIITIAIIACI':return array('anticonstitutionnel');
case'AIITIAAIIATITIITIAAIICI':return array('anticonstitutionnel');
case'AIITICAIIATITIITIAAIICI':return array('anticonstitutionnel');
case'AIITIAAIICTITIITIAAIICI':return array('anticonstitutionnel');
case'AIITICAIICTITIITIAAIICI':return array('anticonstitutionnel');
case'AIITIAAAATITIITIAIIIICI':return array('anticonstitutionnel');
case'AIITICAAATITIITIAIIIICI':return array('anticonstitutionnel');
case'AIITIAAACTITIITIAIIIICI':return array('anticonstitutionnel');
case'AIITICAACTITIITIAIIIICI':return array('anticonstitutionnel');
case'AIITIAAIIIIAAIIAMAIITAI':return array('antigouvernemental');
case'AIITICAIIIIAAIIAMAIITAI':return array('antigouvernemental');
case'AIITIAAIIIICAIIAMAIITAI':return array('antigouvernemental');
case'AIITICAIIIICAIIAMAIITAI':return array('antigouvernemental');
case'AIITIAAIIIIAAIICMAIITAI':return array('antigouvernemental');
case'AIITICAIIIIAAIICMAIITAI':return array('antigouvernemental');
case'AIITIAAIIIICAIICMAIITAI':return array('antigouvernemental');
case'AIITICAIIIICAIICMAIITAI':return array('antigouvernemental');
case'AIITIAAIIIIAAIIAMCIITAI':return array('antigouvernemental');
case'AIITICAIIIIAAIIAMCIITAI':return array('antigouvernemental');
case'AIITIAAIIIICAIIAMCIITAI':return array('antigouvernemental');
case'AIITICAIIIICAIIAMCIITAI':return array('antigouvernemental');
case'AIITIAAIIIIAAIICMCIITAI':return array('antigouvernemental');
case'AIITICAIIIIAAIICMCIITAI':return array('antigouvernemental');
case'AIITIAAIIIICAIICMCIITAI':return array('antigouvernemental');
case'AIITICAIIIICAIICMCIITAI':return array('antigouvernemental');
default: return array();}}
?>