<?php
function gwc_coupable_haut_maj_11_IT($code){switch($code){
case'ITAIIAIIIIA':return array('italienne');
case'ITAIICIIIIA':return array('italienne');
case'ITAIIAIIIIC':return array('italienne');
case'ITAIICIIIIC':return array('italienne');
case'ITAIIAIIAAA':return array('italiennes');
case'ITAIICIIAAA':return array('italiennes');
case'ITAIIAAIIAA':return array('italiennes');
case'ITAIICAIIAA':return array('italiennes');
case'ITAIIAIIACA':return array('italiennes');
case'ITAIICIIACA':return array('italiennes');
case'ITAIIAAIICA':return array('italiennes');
case'ITAIICAIICA':return array('italiennes');
case'ITAIIAIIAAC':return array('italiennes');
case'ITAIICIIAAC':return array('italiennes');
case'ITAIIAAIIAC':return array('italiennes');
case'ITAIICAIIAC':return array('italiennes');
case'ITAIIAIIACC':return array('italiennes');
case'ITAIICIIACC':return array('italiennes');
case'ITAIIAAIICC':return array('italiennes');
case'ITAIICAIICC':return array('italiennes');
case'ITIIIAAAIAA':return array('itineraire');
case'ITIIICAAIAA':return array('itineraire');
case'ITIIIAAAIAC':return array('itineraire');
case'ITIIICAAIAC':return array('itineraire');
case'ITIAAAAIAAA':return array('itineraires');
case'ITIACAAIAAA':return array('itineraires');
case'ITIAAAAIACA':return array('itineraires');
case'ITIACAAIACA':return array('itineraires');
case'ITIAAAAIAAC':return array('itineraires');
case'ITIACAAIAAC':return array('itineraires');
case'ITIAAAAIACC':return array('itineraires');
case'ITIACAAIACC':return array('itineraires');
case'ITIIIAAAIIT':return array('itinerant');
case'ITIIICAAIIT':return array('itinerant');
case'ITIIAIIAIIA':return array('ljubljana');
case'ITIIAITAIIA':return array('ljubljana');
default: return array();}}
?>