<?php
function gwc_coupable_haut_min_11_di($code){switch($code){
case'dioholioiio':return array('diabolique');
case'diototiiooo':return array('dictatures');
case'diototioiio':return array('dietetique');
case'diffomotioo':return array('diffamation');
case'diffooooooo':return array('differences');
case'diffoooooio':return array('differencie');
case'diffooootoo':return array('differentes');
case'diffioiilto':return array('difficulte');
case'diooitoiooo':return array('dignitaires');
case'dimioiitioo':return array('diminution');
case'dioootomoot':return array('directement');
case'dioootoiioo':return array('directeurs');
case'dioootiiioo':return array('directives');
case'dioiooootoo':return array('dirigeantes');
case'diooioliooo':return array('disciplines');
case'diooooditoo':return array('discrediter');
case'dioooimiooo':return array('discriminer');
case'diooiiooioo':return array('discussion','dissuasion');
case'diooiitohlo':return array('discutable');
case'dioooooitoo':return array('disparaitre');
case'diooooitioo':return array('disparition','disposition');
case'diooooooioo':return array('dispensaire');
case'diooooihloo':return array('disponibles');
case'dioooooioot':return array('disposaient');
case'diooooitifo':return array('dispositifs');
case'diooiiottoo':return array('disquettes');
case'dioooooiooo':return array('dissensions');
case'diooimiiloo':return array('dissimuler');
case'diotillooio':return array('distillerie');
case'diotiootioo':return array('distinction');
case'diotiooiioo':return array('distinguer');
case'diotoooiooo':return array('distorsions');
case'diotoootioo':return array('distraction');
case'diotooiioot':return array('distrayant');
case'diotoihiioo':return array('distribuee','distribuer','distribues');
case'dithiioomho':return array('dithyrambe');
case'diiiooooooo':return array('divergence');
case'diiioooifio':return array('diversifie');
case'diiiidoodoo':return array('dividendes');
case'diiohoooiio':return array('dunkerque');
case'diiolioiioo':return array('dupliquer');
case'diioohilito':return array('durabilite');
case'diioooldoof':return array('dusseldorf');
case'diioomioiio':return array('dynamique');
default: return array();}}
?>