<?php
function gwc_coupable_haut_min_9_hi($code){switch($code){
case'hihlioiio':return array('biblique');
case'hioooooot':return array('bienseant');
case'hioloiiii':return array('bigleux');
case'hilotoool':return array('bilateral');
case'hiliooiio':return array('bilingue');
case'hioiiotto':return array('biquette');
case'hiohoooii':return array('birkenau');
case'hioooooii':return array('biscornu');
case'hitiimooo':return array('bitumage');
case'hiiioiioo':return array('bivouac');
case'hiiooooot':return array('bucarest');
case'hiiohoooo':return array('bucheron');
case'hiiohoiio':return array('bucheur');
case'hiidoooot':return array('budapest');
case'hiilooooo':return array('bulgares');
case'hiiloooio':return array('bulgarie');
case'hiillotio':return array('bulletin');
case'hiioiiioo':return array('burkina');
case'hiioiiodi':return array('burundi');
case'hiioioooo':return array('business');
case'hiotoiooo':return array('histoires');
case'hiotooioo':return array('historien');
case'hitohoooh':return array('hitchcock');
case'hiiiooool':return array('hivernal');
case'hiiilooio':return array('huilerie');
case'hiiiooioo':return array('huissier');
case'hiiitiomo':return array('huitieme');
case'hiiliiloo':return array('hululer');
case'hiimoiooo':return array('humaines');
case'hiimooito':return array('humanite');
case'hiimootoo':return array('humecter');
case'hiimidito':return array('humidite');
case'hiimilioo':return array('humilier');
case'hiimilito':return array('humilite');
case'hiihoidoo':return array('hybrides');
case'hiiotooio':return array('hysterie');
case'hidoooooo':return array('kidnapper');
case'hilomotoo':return array('kilometre');
default: return array();}}
?>