<?php
function gwc_coupable_haut_min_9_lo($code){switch($code){
case'lohoiiooo':return array('labourer');
case'lootifooo':return array('lactifere');
case'lootioiio':return array('lactique');
case'looiiotoo':return array('lacustre');
case'loiooiiii':return array('laineux');
case'loitoiiii':return array('laiteux');
case'loooomoot':return array('lancement','largement');
case'loooiooot':return array('lancinant');
case'looooooii':return array('lapereau');
case'looiiollo':return array('laquelle');
case'loomoiioo':return array('larmoyer');
case'loooiiooo':return array('larousse');
case'lotitiido':return array('latitude');
case'loiioooto':return array('laureats');
case'loiiooooo':return array('laurence','lausanne');
case'looooiiim':return array('lecanium');
case'looooiiot':return array('lecanuet');
case'lootoiioo':return array('lecteurs','lenteurs');
case'lootiiooo':return array('lectures');
case'lofohiioo':return array('lefebvre');
case'loooliooo':return array('legaliser');
case'loootoioo':return array('legataire','locataire');
case'looitimoo':return array('legitimer','legitimes');
case'loodomoio':return array('lendemain');
case'looiooood':return array('leningrad');
case'looioiomo':return array('leninisme');
case'looioioto':return array('leniniste');
case'lootomoot':return array('lentement');
case'loooiiolo':return array('lesquels');
case'loooiiioo':return array('lessiver');
case'lothoooio':return array('lethargie');
case'loiiioiio':return array('lexique');
case'looolitoo':return array('localites');
case'looiitioo':return array('locution');
case'looomooto':return array('logements');
case'looioiolo':return array('logiciels');
case'looioiioo':return array('logiques');
case'loiotoioo':return array('lointaine','lointains');
case'loodooioo':return array('londonien');
case'loootomoo':return array('longtemps');
case'loiioiito':return array('loyaute');
default: return array();}}
?>