<?php
function gwc_coupable_haut_maj_5_II($code){switch($code){
case'IIAIA':return array('haie','hair','hale','hein','nain','noir','unie','unir','unis','vain','vais','velo','voie','voir','vois','vole','vols');
case'IIAIC':return array('haie','hale','naif','unie','unis','vais','voie','vois','vole','vols');
case'IIAII':return array('hall','han','lien','lieu','lion','neil','non','van','veil','yak','yen');
case'IIAAA':return array('hans','horn','hors','liban','libre','liees','liege','liens','ligne','linda','linge','lions','lires','lisse','nage','nasa','nase','nees','neon','noce','nord','unes','urss','user','vans','vase','vend','vers','yang','yard','yens','yoga');
case'IIAAC':return array('hans','hors','libre','liees','liege','liens','ligne','linge','lions','lires','lisse','nage','nase','nees','nerf','noce','unes','urss','vans','vase','vers','yang','yens');
case'IIATA':return array('hate','hote','liste','nets','note','veto','vote');
case'IIATC':return array('hate','hote','liste','nets','note','vote');
case'IICIA':return array('hein','velo');
case'IIIAA':return array('hier','inde','inne','inra','ivan','ivre','juan','judo','juge','jupe','jura','jure','lilas','lune','lyon','nice','nier','nina','vice','vide','vies','vins','visa','vise','vlan');
case'IIICA':return array('hier','info','juge','nice','nier','vice','vies','vifs','visa','vise');
case'IIAMA':return array('home','noms','vamp');
case'IIAMC':return array('home','noms');
case'IIIIA':return array('hun','juin','kilo','lille','line','luis','nue','nus','une','vue','vus');
case'IIIAC':return array('inde','inne','ivre','juge','jupe','jure','lilas','lune','nice','vice','vide','vies','vins','vise');
case'IIICC':return array('juge','nice','vice','vies','vifs','vise');
case'IIIIC':return array('juif','lille','line','luis','nue','nus','une','vue','vus');
case'IIITA':return array('jute','vite');
case'IIITC':return array('jute','vite');
case'IIAAI':return array('karl','noel','vrai');
case'IIIIT':return array('kilt');
case'IIAAT':return array('liant','vent','vert','vont');
case'IICAA':return array('liees','liege','liens','ligne','lisse','nees','neon','user','vend','vers','yens');
case'IIACA':return array('liees','liege','linge','lires','lisse','nage','nasa','nase','nees','noce','unes','urss','user','vase','yoga');
case'IICCA':return array('liees','liege','lisse','nees','user');
case'IICAC':return array('liees','liege','liens','ligne','lisse','nees','nerf','vers','yens');
case'IIACC':return array('liees','liege','linge','lires','lisse','nage','nase','nees','noce','unes','urss','vase');
case'IICCC':return array('liees','liege','lisse','nees');
case'IICII':return array('lien','lieu','neil','veil','yen');
case'IIMAA':return array('limer');
case'IIMCA':return array('limer');
case'IICTA':return array('liste','nets','veto');
case'IICTC':return array('liste','nets');
case'IIAZT':return array('liszt');
case'IICZT':return array('liszt');
case'IITAA':return array('litre');
case'IITAC':return array('litre');
case'IIAIT':return array('nait','unit','voit');
case'IIAZI':return array('nazi');
case'IIACI':return array('noel');
case'IIIII':return array('nul','uni','vin');
case'IICAT':return array('vent','vert');
case'IIIAT':return array('vint');
case'IIIAI':return array('viol');
case'IIIIM':return array('wim');
default: return array();}}
?>