<?php
function gwc_coupable_bas_min_12_gi($code){switch($code){
case'gigoiiiaaqaa':return array('gigantesque');
case'gigoiiaaaqaa':return array('gigantesque');
case'gigoiiiaaqoa':return array('gigantesque');
case'gigoiiaaaqoa':return array('gigantesque');
case'giaaoiaiaiia':return array('giscardiens');
case'giaaoioiaiia':return array('giscardiens');
case'giaaoiaaaiia':return array('giscardiens');
case'giaaoioaaiia':return array('giscardiens');
case'giaaiiiaiiia':return array('gisements');
case'giaaiiiaiiaa':return array('gisements');
case'gioiiaiiiaia':return array('grandmere');
case'gioiioiiiaia':return array('grandmere');
case'gioiiapopiai':return array('grattepapier');
case'gioaiapopiai':return array('grattepapier');
case'gioiaapopiai':return array('grattepapier');
case'gioaaapopiai':return array('grattepapier');
case'gioiiapopaai':return array('grattepapier');
case'gioaiapopaai':return array('grattepapier');
case'gioiaapopaai':return array('grattepapier');
case'gioaaapopaai':return array('grattepapier');
case'giobaiiiaiii':return array('gravement');
case'giobaiiiaiia':return array('gravement');
case'giobiioiiaii':return array('gravitation');
case'giobaioiiaii':return array('gravitation');
case'giobiaoiiaii':return array('gravitation');
case'giobaaoiiaii':return array('gravitation');
case'giobiioaiaii':return array('gravitation');
case'giobaioaiaii':return array('gravitation');
case'giobiaoaiaii':return array('gravitation');
case'giobaaoaiaii':return array('gravitation');
case'giobiioiaaii':return array('gravitation');
case'giobaioiaaii':return array('gravitation');
case'giobiaoiaaii':return array('gravitation');
case'giobaaoiaaii':return array('gravitation');
case'giobiioaaaii':return array('gravitation');
case'giobaioaaaii':return array('gravitation');
case'giobiaoaaaii':return array('gravitation');
case'giobaaoaaaii':return array('gravitation');
case'giaiiaaiaiaa':return array('grenobloise');
case'giaiiaaiaaaa':return array('grenobloise');
case'giiiiaiiiiai':return array('griffonner');
case'giaiiaiiiiai':return array('griffonner');
default: return array();}}
?>