<?php
function gwc_coupable_bas_min_12_jo($code){switch($code){
case'jogaiiiaiiia':return array('jugements');
case'jogaiiiaiiaa':return array('jugements');
case'joiiaiaiiaii':return array('juridiction');
case'joiaaiaiiaii':return array('juridiction');
case'joiioiaiiaii':return array('juridiction');
case'joiaoiaiiaii':return array('juridiction');
case'joiiaaaiiaii':return array('juridiction');
case'joiaaaaiiaii':return array('juridiction');
case'joiioaaiiaii':return array('juridiction');
case'joiaoaaiiaii':return array('juridiction');
case'joiiaiaaiaii':return array('juridiction');
case'joiaaiaaiaii':return array('juridiction');
case'joiioiaaiaii':return array('juridiction');
case'joiaoiaaiaii':return array('juridiction');
case'joiiaaaaiaii':return array('juridiction');
case'joiaaaaaiaii':return array('juridiction');
case'joiioaaaiaii':return array('juridiction');
case'joiaoaaaiaii':return array('juridiction');
case'joiiaiaiaaii':return array('juridiction');
case'joiaaiaiaaii':return array('juridiction');
case'joiioiaiaaii':return array('juridiction');
case'joiaoiaiaaii':return array('juridiction');
case'joiiaaaiaaii':return array('juridiction');
case'joiaaaaiaaii':return array('juridiction');
case'joiioaaiaaii':return array('juridiction');
case'joiaoaaiaaii':return array('juridiction');
case'joiiaiaaaaii':return array('juridiction');
case'joiaaiaaaaii':return array('juridiction');
case'joiioiaaaaii':return array('juridiction');
case'joiaoiaaaaii':return array('juridiction');
case'joiiaaaaaaii':return array('juridiction');
case'joiaaaaaaaii':return array('juridiction');
case'joiioaaaaaii':return array('juridiction');
case'joiaoaaaaaii':return array('juridiction');
case'joaiaiiiaiii':return array('justement');
case'joaaaiiiaiii':return array('justement');
case'joaiaiiiaiia':return array('justement');
case'joaaaiiiaiia':return array('justement');
default: return array();}}
?>