<?php
function gwc_coupable_bas_maj_14_IO($code){switch($code){
case'IOIIOLIIILIIIO':return array('fondements');
case'IOIIIIIIILIILO':return array('formalites');
case'IOIIIIIIIIIOII':return array('formation');
case'IOIIIIIIOIIOLL':return array('formidable');
case'IOOIIIIIILLLII':return array('fourmiller');
case'IOOIIIIIOOLIII':return array('fournissent');
case'IOOIIIIIOOLOII':return array('fournisseur');
case'IOOIIIIIIOIILO':return array('fournitures');
case'IOIILIIIIILLLO':return array('funerailles');
case'IOIOOOIIIIILII':return array('poissonnier');
case'IOLIOIIIIOIIIL':return array('polychrome');
case'IOLILIIIIOIIIL':return array('polychrome');
case'IOLIIIIOIIIQOL':return array('polyphonique');
case'IOIIILILOILLLO':return array('portefeuilles');
case'IOOIOIIIIILIIL':return array('pouponniere');
case'IOOIIOLIIIIIOL':return array('pourcentage');
case'IOOIILLIIIIIOL':return array('pourcentage');
case'IOOIIIIIIILIII':return array('pourraient');
case'IOOIIOOIVIIIII':return array('poursuivant');
case'IOIOIIIIIIIILO':return array('psychiatres');
case'IOILIIIIIIIILO':return array('psychiatres');
case'IOIOIIIIIIIIIL':return array('psychiatrie');
case'IOILIIIIIIIIIL':return array('psychiatrie');
case'IOIOIIOLOOIQOL':return array('psychologique');
case'IOILIIOLOOIQOL':return array('psychologique');
case'IOOLIOIIIIOIIO':return array('publications');
case'IOOLILIIIIOIIO':return array('publications');
case'IOOLIOIIIIIIIL':return array('publicitaire');
case'IOOLILIIIIIIIL':return array('publicitaire');
case'IOOIOOIIOLIIIL':return array('pudibonderie');
case'IOIIIIIIOIIIII':return array('tonitruant');
case'IOIIILLIIILIII':return array('totalement');
case'IOIIILIIIIIIIL':return array('totalitaire');
case'IOOIIIILOIOQOL':return array('tournedisque');
case'IOOIIOIOOIIIII':return array('toutpuissant');
default: return array();}}
?>