<?php
function gwc_coupable_bas_maj_15_IL($code){switch($code){
case'ILLIOIIIIIIOIIO':return array('felicitations');
case'ILLILIIIIIIOIIO':return array('felicitations');
case'ILIIIIILIIILIII':return array('fermement');
case'ILIIIIIIILLLOII':return array('ferrailleur');
case'ILIIIIOVIIIIIIL':return array('ferroviaire');
case'ILIIIIIOOIIIIII':return array('flamboyant');
case'ILLOOIIIIIIIOII':return array('illustration');
case'ILIILIIIIIIIOII':return array('penetration');
case'ILIIIOLLIIILIII':return array('peniblement');
case'ILIILIIIIIOIIIL':return array('peremptoire');
case'ILIILOIIIOIIIII':return array('perestroika');
case'ILIIIIIILIIIQOL':return array('peripherique');
case'ILIIIIIIIIILIII':return array('permanent');
case'ILIIIIILIIIIIII':return array('permettant');
case'ILIIQOIOIIIOIIO':return array('perquisitions');
case'ILIIOLVLIIIIIII':return array('perseverant');
case'ILIIOOIIIIIIOLO':return array('personnages');
case'ILIIOOIIIILLLLO':return array('personnelles');
case'ILOLILIIOOIIIIL':return array('pesepersonne');
case'ILIIIIIIIIIOIIO':return array('plantations');
case'ILLOIIIIIOIILII':return array('pleurnicher');
case'ILLOIIIIILIILII':return array('pleurnicher');
case'ILOIIIIOLOOIQOL':return array('technologique');
case'ILLIIIIOLOOIQOL':return array('technologique');
case'ILOIIIIOLOOIOIL':return array('technologiste');
case'ILLIIIIOLOOIOIL':return array('technologiste');
case'ILLLIIIOIIIQOLO':return array('telephoniques');
case'ILIIIOIOIIIIOLO':return array('temoignages');
case'ILIIIILIIIIIIOL':return array('temperance');
case'ILIIIILIIIIIILL':return array('temperance');
case'ILIIIIOIIIIIIIL':return array('temporaire');
case'ILIIOIIIIOILOII':return array('tendancieux');
case'ILIIOIIIILILOII':return array('tendancieux');
case'ILIIIIIIIIIIOII':return array('terminaux');
case'ILIIIIIIOIIIIIL':return array('territorial');
case'ILIIIIOIIIOIIIL':return array('terrorisme');
default: return array();}}
?>