<?php
function gwc_coupable_bas_maj_15_IO($code){switch($code){
case'IOIIOIIOIIIILII':return array('fonctionner');
case'IOIILIIOIIIILII':return array('fonctionner');
case'IOIIIIIIIIIIIIL':return array('forfaitaire');
case'IOIIIIIIIILOIIO':return array('formateurs');
case'IOIIIIIIIIIOIIO':return array('formations');
case'IOIIIIIOLIIIIIL':return array('formulaire');
case'IOIIIIIOIIILOII':return array('fornicateur');
case'IOIIIIILIIILOII':return array('fornicateur');
case'IOOIIIIIOOIIIII':return array('fournissant');
case'IOOIIIIIOOLOIIO':return array('fournisseurs');
case'IOIIIIVLIIILIII':return array('furtivement');
case'IOIIIILLILIIIIL':return array('israelienne');
case'IOLIIQOLIIILIII':return array('poetiquement');
case'IOLIILOIIIIIQOL':return array('polytechnique');
case'IOLIILLIIIIIQOL':return array('polytechnique');
case'IOIIIIIILOLIIII':return array('pommedepin');
case'IOIIILOIIOIIOLO':return array('portebagages');
case'IOOIIIVLIIILIII':return array('positivement');
case'IOOOIOLLIIILIII':return array('possiblement');
case'IOOIIOLIIIIIOLO':return array('pourcentages');
case'IOOIILLIIIIIOLO':return array('pourcentages');
case'IOOIIOIIIIOOLII':return array('pourchasser');
case'IOOIILIIIIOOLII':return array('pourchasser');
case'IOOIIIIIIILLIIO':return array('pourparlers');
case'IOIOIIOLOOIQOLO':return array('psychologiques');
case'IOILIIOLOOIQOLO':return array('psychologiques');
case'IOOLIOIIIIIIILO':return array('publicitaires');
case'IOOLILIIIIIIILO':return array('publicitaires');
case'IOOLIQOLIIILIII':return array('publiquement');
case'IOLIIIOIIIIIIIL':return array('pulmonaire');
case'IOOILLIIIIIIIIL':return array('pusillanime');
case'IOIIIILIIIOLOII':return array('torrentueux');
case'IOOIIIIILIIILII':return array('tourmenter');
case'IOIIIOOIIIIIIIL':return array('toxicomane');
case'IOIIILOIIIIIIIL':return array('toxicomane');
default: return array();}}
?>