<?php
function gwc_coupable_bas_maj_19_OO($code){switch($code){
case'OOIIIOIIIIOLIIILIII':return array('bombardement');
case'OOOLLVLIIOLIIILIIIO':return array('bouleversements');
case'OOIILIIOOIIIIIIQOLO':return array('bureaucratiques');
case'OOIILIIOLIIIIIIQOLO':return array('bureaucratiques');
case'OOIIIIIIIIIIOIIIIIO':return array('commandants');
case'OOIIIIIILIIOLIIOIII':return array('commenceront');
case'OOIIIIIILIILLIIOIII':return array('commenceront');
case'OOIIIIIILIIIIIIIILO':return array('commentaires');
case'OOIIIIIIIOOIIIIIIII':return array('commissariat');
case'OOIIIIIIOIIWLIILIII':return array('commonwealth');
case'OOIIIIIIIIIIIIILIII':return array('compartiment');
case'OOIIIIOIIILIIILIIIO':return array('comportements');
case'OOIIIIIILIILIIOIOII':return array('comprehension');
case'OOIIOLIIIIIIIIIOIIO':return array('concentrations');
case'OOIILLIIIIIIIIIOIIO':return array('concentrations');
case'OOIIOIIIIIIIIIIIOII':return array('condamnation');
case'OOIIIOIIIIILIIILIII':return array('conformement');
case'OOIIOOIIIIIIIIILOII':return array('consommateur');
case'OOIIOOIIIIIIIIIIOII':return array('consommation');
case'OOIIOIIIOIIOIIIILLO':return array('constitutionnels');
case'OOIIILIIIIOIIIIIIIL':return array('contemporaine');
case'OOIIILIIIIOIIIIIIIO':return array('contemporains');
case'OOIIIIIIIOIOIOIIILO':return array('contradictoires');
case'OOIIIIIIIOILIOIIILO':return array('contradictoires');
case'OOIIIIIIIIOIIIIIIIL':return array('contraignante');
case'OOIIVLIIIIOIIIILLLL':return array('conventionnelle');
case'OOIIIOIILLLLIIILIII':return array('corporellement');
case'OOIIIILOIIOIIIILLLL':return array('correctionnelle');
case'OOIIIILLIIOIIIILLLL':return array('correctionnelle');
case'OOIIIILLIIIIOIIIILL':return array('correlationnel');
case'OOIIIILOIOIIOIIIIOL':return array('correspondance');
case'OOIIIILOIOIIOIIIILL':return array('correspondance');
case'OOIIIILOIOIIOIIIIIL':return array('correspondante');
case'OOIIIILOIOIIOIIIIIO':return array('correspondants');
case'OOOIIIIOLOOLIIILIII':return array('courageusement');
case'OOIIOIOLLOOLIIILIII':return array('scrupuleusement');
case'OOLLIIIILLLLIIILIII':return array('solennellement');
case'OOIIIIIOLOOLIIILIII':return array('somptueusement');
case'OOOIIIIIILIIIIILIII':return array('souhaiteraient');
case'OOIILLIIILIIIIIIIIL':return array('supplementaire');
case'OOIILIIOLIILIIILIII':return array('surendettement');
default: return array();}}
?>