<?php
function gwc_centrale_12_AA($code){switch($code){
case'AAABHABAIQUB':return array('anachronique');
case'AAABHABAIBMB':return array('anachronisme');
case'AABIBAABMBAT':return array('anciennement');
case'AABBLYBIBAAB':return array('andelysienne');
case'AABABBBABBBB':return array('androgeneses');
case'AABMBABBBMBA':return array('anemonedemer');
case'AABBTHBBIAAT':return array('anesthesiant');
case'AABBTHBBIBTB':return array('anesthesiste');
case'AAAIVBABAIAB':return array('anniversaire');
case'AAABABIATIBA':return array('annonciation');
case'AAAUBLLBMBAT':return array('annuellement');
case'AABAMALBMBAT':return array('anormalement');
case'AATBBILUVIBA':return array('antediluvien');
case'AATIBIBTIQUB':return array('antibiotique');
case'AATIBIPATIBA':return array('anticipation');
case'AATIBLBAIBAL':return array('anticlerical');
case'AATIBTATIQUB':return array('antietatique');
case'AATIFABBIBMB':return array('antifascisme');
case'AATIFABBIBTB':return array('antifasciste');
case'AATIPATHIQUB':return array('antipathique');
case'AATIBBPTIQUB':return array('antiseptique');
case'AABHBBLBBUBB':return array('archeologues');
case'AABHITBBTUAB':return array('architecture');
case'AAIBTBBAATIB':return array('aristocratie');
case'AAITHMBTIQUB':return array('arithmetique');
case'AAABBTATIBAB':return array('arrestations');
case'AAAIBABBAABB':return array('arrieregarde');
case'AATIBULATIBA':return array('articulation');
case'AATIFIBIBLLB':return array('artificielle');
case'AAHHITBHBVAA':return array('nakhitchevan');
case'AAABBBBLLAAB':return array('narcodollars');
case'AATIBAALIBMB':return array('nationalisme');
case'AATIBAALIBTB':return array('nationaliste');
case'AATIBAALITBB':return array('nationalites');
case'AABBBMPABABA':return array('raccompagner');
case'AABIBALBMBAT':return array('radicalement');
case'AABAILLAABIA':return array('ragaillardir');
case'AAIBBAAABLBB':return array('raisonnables');
case'AAIBBAABMBAT':return array('raisonnement');
case'AAMIFIBATIBA':return array('ramification');
case'AAPATAIBMBAT':return array('rapatriement');
case'AATIFIBATIBA':return array('ratification');
case'AATIBAABMBAT':return array('rationnement');
case'AATTABHBMBAT':return array('rattachement');
case'AAVITAILLBUA':return array('ravitailleur');
default: return array();}}
?>