<?php
function gwc_coupable_bas_maj_7_VI($code){switch($code){
case'VIIOIIL':return array('vache');
case'VIILIIL':return array('vache','vipere');
case'VIIOOLO':return array('vagues');
case'VIIILLL':return array('vaille');
case'VIILIOL':return array('valide','valise');
case'VIILLLL':return array('vallee');
case'VIILLLI':return array('vallet');
case'VIILOLO':return array('values');
case'VIIIIII':return array('vamp');
case'VIIIIIL':return array('varie','vraie');
case'VIIOQOL':return array('vasque');
case'VIIOILO':return array('vastes');
case'VIOILII':return array('vicier');
case'VILILII':return array('vicier');
case'VIOIOII':return array('victor','vision');
case'VILIOII':return array('victor');
case'VILILLL':return array('vieille');
case'VILILLI':return array('vieilli');
case'VILIIOL':return array('vierge');
case'VIOLLII':return array('violer');
case'VIOLOII':return array('violon');
case'VIIILII':return array('virer');
case'VIOIIOL':return array('visage');
case'VIOIIII':return array('visait');
case'VIOLIII':return array('visent');
case'VIOIOLL':return array('visible');
case'VIOIILO':return array('visites');
case'VIOOLII':return array('visser');
case'VIILOOL':return array('vitesse');
case'VIIIILO':return array('vitres');
case'VIVIIOL':return array('vivace');
case'VIVIILL':return array('vivace');
case'VIVIIII':return array('vivait','vivra');
case'VIVLIII':return array('vivent');
case'VIVILII':return array('vivien','vivier');
case'VIVOIIO':return array('vivons');
case'VIVIILO':return array('vivres');
case'VIIIIIO':return array('vrais');
default: return array();}}
?>