<?php
function gwc_centrale_7_BT($code){switch($code){
case'BTABLIB':return array('etablie','etablis');
case'BTABLIA':return array('etablir');
case'BTABLIT':return array('etablit');
case'BTABBAB':return array('etagere');
case'BTAIBAT':return array('etaient');
case'BTALABB':return array('etalage');
case'BTAMABB':return array('etamage');
case'BTAABHB':return array('etanche');
case'BTBABAB':return array('etendre');
case'BTBABUB':return array('etendue');
case'BTBAABL':return array('eternel');
case'BTHIQUB':return array('ethique');
case'BTIBAAB':return array('etienne');
case'BTBILBB':return array('etoiles');
case'BTBAABA':return array('etonner');
case'BTBAABB':return array('etonnes');
case'BTBUABI':return array('etourdi');
case'BTAAABB':return array('etrange');
case'BTABAAB':return array('etrenne');
case'BTAILLB':return array('etrille');
case'BTAIQUB':return array('etrique');
case'BTABITB':return array('etroite','etroits');
case'BTUBIBB':return array('etudiee','etudies','studios');
case'BTUBIBA':return array('etudier');
case'BTTBMAA':return array('ottoman');
case'BTABLBB':return array('stables');
case'BTABIUM':return array('stadium');
case'BTALIAB':return array('staline');
case'BTATIBA':return array('station');
case'BTATUBA':return array('statuer');
case'BTATUAB':return array('stature');
case'BTATUTB':return array('statuts');
case'BTBBPLB':return array('steeple');
case'BTBPHAA':return array('stephan');
case'BTBPHBA':return array('stephen');
case'BTBAILB':return array('sterile');
case'BTBWAAT':return array('stewart');
case'BTIPULB':return array('stipule');
case'BTBBHBA':return array('stocker');
case'BTBPPBA':return array('stopper');
case'BTAAUBB':return array('strauss');
case'BTAIBTB':return array('stricte');
case'BTUPBUA':return array('stupeur');
case'BTUPIBB':return array('stupide');
case'BTUPABB':return array('stupres');
default: return array();}}
?>