<?php
function gwc_coupable_bas_maj_6_IO($code){switch($code){
case'IOLIOO':return array('foetus');
case'IOIIIL':return array('foire','fonte','forte','furie','poire','porte','tome','total');
case'IOLILO':return array('folies','poetes');
case'IOLLLO':return array('folles');
case'IOIIOL':return array('fonce','fonde','force','forge','purge','torse');
case'IOIILL':return array('fonce','force','futile');
case'IOIIOO':return array('fonds','poitou','tonus','turbo');
case'IOIILI':return array('foret','furet','poney');
case'IOIIIO':return array('forts','poing','ponts','porto','ports','tokyo','tunis','tuyau');
case'IOOIIO':return array('fouad','fours','fuchs','touffu','tours','young');
case'IOOOOL':return array('fougue','pousse');
case'IOOIII':return array('fouir','iouri');
case'IOOLLL':return array('foulee','isolee');
case'IOOLLO':return array('foules','fusees','isoles','posees');
case'IOOIOO':return array('foutus');
case'IOILII':return array('foyer');
case'IOLIIO':return array('fuchs');
case'IOIILO':return array('fuites','icipeu','pures');
case'IOOILO':return array('fusils','postes','toutes');
case'IOIOII':return array('futur');
case'IOLIII':return array('ibert','polir','tuent');
case'IOLOII':return array('iceux','tueur');
case'IOOIIL':return array('icone','poche','puche','touffe');
case'IOLIIL':return array('ideal','isere','poche','puche','tulipe');
case'IOIOIL':return array('idiote','popote');
case'IOOOLO':return array('issues');
case'IOLOIL':return array('poesie');
case'IOIIII':return array('point','potin','tsar','york');
case'IOIOOL':return array('poisse','puisse');
case'IOIOOI':return array('poissy');
case'IOLIOL':return array('police');
case'IOLILL':return array('police');
case'IOOLII':return array('poser','touer');
case'IOOLLI':return array('poulet');
case'IOOLIL':return array('poulie','public','publie');
case'IOOILL':return array('poupee');
case'IOOVLZ':return array('pouvez');
case'IOLOOO':return array('pseudo');
case'IOOLIO':return array('public');
case'IOZZLL':return array('puzzle');
case'IOOOII':return array('todor');
case'IOILLO':return array('toiles');
case'IOOOIO':return array('toubib');
case'IOOILI':return array('toupet');
default: return array();}}
?>