<?php
function gwc_coupable_bas_maj_6_LO($code){switch($code){
case'LOOOII':return array('cocon','essor');
case'LOLOII':return array('cocon','coeur','lueur');
case'LOIIOL':return array('cohue','conge','corde','corse','cupide');
case'LOIIIL':return array('coiffe','conte','cuire','curie','ecrie','egypte','loire','lome','loyal','luire');
case'LOIIIO':return array('coins','corps');
case'LOLIII':return array('colin','eclat');
case'LOLLLI':return array('collet');
case'LOIIOO':return array('concu','congo','echos','longo','longs');
case'LOIILO':return array('concu','copies','echec','luttes');
case'LOIIII':return array('cora','ecrit','edith','lopin');
case'LOIILL':return array('coree','ecale','echec','egale');
case'LOOIII':return array('costa','court','essai');
case'LOILLO':return array('cotees');
case'LOIOII':return array('coton');
case'LOOOOO':return array('coucou');
case'LOOLOO':return array('coucou');
case'LOOLLL':return array('coulee');
case'LOOILL':return array('coupee','couple');
case'LOOILO':return array('coupes','essieu');
case'LOOIIO':return array('cours','couru','lourd','lucas');
case'LOOLII':return array('cuber','loger','louer');
case'LOIOOL':return array('cuisse');
case'LOLOLO':return array('culsec');
case'LOLOLL':return array('culsec');
case'LOLIIL':return array('ebene','local','luette');
case'LOLOIL':return array('eclope');
case'LOLOOL':return array('ecluse');
case'LOOLLO':return array('ecoles');
case'LOOOOL':return array('ecosse');
case'LOOOIL':return array('ecoute','essuye');
case'LOOLIL':return array('ecueil');
case'LOLIOL':return array('eglise','lucide');
case'LOILOL':return array('espece');
case'LOILLL':return array('espece');
case'LOQOII':return array('esquif');
case'LOOIIL':return array('local');
case'LOILII':return array('loyer');
case'LOLIIO':return array('lucas');
case'LOOIOL':return array('lucide');
case'LOOWIO':return array('ludwig');
case'LOIIOI':return array('lundi');
default: return array();}}
?>