<?php
function gwc_centrale_6_FB($code){switch($code){
case'FBBVAB':return array('febvre');
case'FBBBAB':return array('fecond');
case'FBBAIB':return array('feerie');
case'FBIATB':return array('feinte');
case'FBLIPB':return array('felipe');
case'FBMMBB':return array('femmes');
case'FBABAB':return array('fendre','ferons','fondre');
case'FBAAIT':return array('ferait');
case'FBAMBB':return array('fermee','fermes','formee','formes');
case'FBAMBA':return array('fermer','former');
case'FBABBB':return array('feroce','fondee','fondes','forcee','forces');
case'FBABAT':return array('feront');
case'FBAABB':return array('ferree','forage');
case'FBAABA':return array('ferrer');
case'FBBBBB':return array('fessee','fesses');
case'FBBBBA':return array('fesser');
case'FBBTIA':return array('festin');
case'FBUTAB':return array('feutre','foutre');
case'FBBTUB':return array('foetus');
case'FBIABB':return array('foires');
case'FBIBBA':return array('foison');
case'FBHHBA':return array('fokker');
case'FBLIBB':return array('folies');
case'FBLLBB':return array('folles');
case'FBABBA':return array('fonder','forcer','forger');
case'FBABIA':return array('forcir');
case'FBABTB':return array('forets');
case'FBAMAT':return array('format');
case'FBAMBL':return array('formel');
case'FBATBB':return array('fortes');
case'FBUBAB':return array('foudre');
case'FBUBUB':return array('fougue');
case'FBULBB':return array('foulee','foules');
case'FBULBA':return array('fouler');
case'FBUABB':return array('fourbe');
case'FBUABI':return array('fourbi');
case'FBUAMI':return array('fourmi');
case'FBUAAI':return array('fourni');
case'FBUTUB':return array('foutus');
case'FBYBAB':return array('foyers');
default: return array();}}
?>