<?php
function gwc_centrale_6_LB($code){switch($code){
case'LBABBA':return array('leader','london');
case'LBBHBA':return array('lecher');
case'LBBBAB':return array('lecons','legere','legers');
case'LBBBUH':return array('ledoux');
case'LBBALB':return array('legale','locale');
case'LBBAUH':return array('legaux','locaux');
case'LBBIBA':return array('legion','lesion');
case'LBBUBA':return array('leguer');
case'LBBUMB':return array('legume');
case'LBMIAB':return array('lemire');
case'LBMBAB':return array('lemond');
case'LBAIAB':return array('lenine');
case'LBABIA':return array('lenoir');
case'LBQUBL':return array('lequel');
case'LBBTBA':return array('lester');
case'LBTTAB':return array('lettre');
case'LBUAAB':return array('leurre');
case'LBVAIA':return array('levain');
case'LBVAAT':return array('levant');
case'LBVBBB':return array('levees');
case'LBVBAT':return array('levent');
case'LBVIBA':return array('levier');
case'LBVABB':return array('levres');
case'LBVUAB':return array('levure');
case'LBZAAB':return array('lezard');
case'LBBBUA':return array('logeur');
case'LBIBIA':return array('loisir');
case'LBABUB':return array('longue');
case'LBAIBT':return array('loriot');
case'LBUBHB':return array('louche');
case'LBUBUA':return array('loueur');
case'LBUPBA':return array('louper');
case'LBUABB':return array('lourde','lourds');
case'LBUVAB':return array('louvre');
case'LBYBAB':return array('loyers');
default: return array();}}
?>