<?php
function gwc_centrale_6_TB($code){switch($code){
case'TBIATB':return array('teinte');
case'TBLLBB':return array('telles');
case'TBLBBA':return array('telson');
case'TBMBIA':return array('temoin');
case'TBMPBB':return array('tempes');
case'TBMPLB':return array('temple');
case'TBAABB':return array('tenace','terres','tonnes');
case'TBAAIT':return array('tenait');
case'TBAAAT':return array('tenant');
case'TBABBA':return array('tendon');
case'TBABAB':return array('tendre','tenere','tenors','tondre','tordre');
case'TBABUB':return array('tendue','tendus');
case'TBABUA':return array('teneur');
case'TBAAIB':return array('tennis');
case'TBATBB':return array('tentee','tentes');
case'TBATBA':return array('tenter');
case'TBAUBB':return array('tenude','tenues');
case'TBAMBB':return array('termes');
case'TBAAIA':return array('ternir');
case'TBATAB':return array('tertre');
case'TBBTBA':return array('tester');
case'TBHTBB':return array('textes');
case'TBILBB':return array('toiles');
case'TBIBBA':return array('toison');
case'TBMATB':return array('tomate');
case'TBMBBB':return array('tombee','tombes');
case'TBMBBA':return array('tomber');
case'TBAABA':return array('tonner');
case'TBABHB':return array('torche');
case'TBATUB':return array('tortue');
case'TBTALB':return array('totale');
case'TBUBIB':return array('toubib');
case'TBUBBA':return array('toubon');
case'TBUBHB':return array('touche');
case'TBUFFB':return array('touffe');
case'TBUFFU':return array('touffu');
case'TBULBA':return array('toulon');
case'TBUPBT':return array('toupet');
case'TBUABB':return array('tourbe');
case'TBUAAB':return array('tourne');
case'TBUTBB':return array('toutes');
case'TBYBTA':return array('toyota');
default: return array();}}
?>