<?php
function gwc_coupable_bas_maj_22_II($code){switch($code){
case'IIOIIOOOIIOIOOLIIILIII':return array('abasourdissement');
case'IIOOOIIIIIIOIILIIILIII':return array('accompagnement');
case'IILOOIIIIIIOIILIIILIII':return array('accompagnement');
case'IIOLOIIIIIIOIILIIILIII':return array('accompagnement');
case'IILLOIIIIIIOIILIIILIII':return array('accompagnement');
case'IIOIIIIIIIOIIIIIILOIIO':return array('administrateurs');
case'IIOIIIIIIIOIIIIIIIOIIO':return array('administrations');
case'IIIIOILIIILOIIIIIILIII':return array('ancientestament');
case'IIIILILIIILOIIIIIILIII':return array('ancientestament');
case'IIIIIIOIIOIOOLIIILIIIO':return array('arrondissements');
case'IIOIOIIIIIIIQOLIIILIII':return array('automatiquement');
case'IIIOIIIIILOLOIIIIOOIIL':return array('hydratedecarbone');
case'IIIOIIIIILOLLIIIIOOIIL':return array('hydratedecarbone');
case'IIIIIIILOOIOIIIIIIIIIL':return array('impressionnante');
case'IIIOOIIIIIILIILIIOIOLL':return array('incomprehensible');
case'IIILOIIIIIILIILIIOIOLL':return array('incomprehensible');
case'IIIOOIIIIIILIILIIOIOII':return array('incomprehension');
case'IIILOIIIIIILIILIIOIOII':return array('incomprehension');
case'IIIOLILIIOIIIIIIIILIII':return array('independamment');
case'IIIOOOIIIIIILIOIIIIOII':return array('industrialisation');
case'IIIOIIIIIIIIIILIIILIII':return array('instantanement');
case'IIIILLLLOIOLLLLIIILIII':return array('intellectuellement');
case'IIIILLLLLIOLLLLIIILIII':return array('intellectuellement');
case'IIIILIIIIIIIIIOILIIILL':return array('interministeriel');
case'IIIIIOIIIIIIILLIIILIII':return array('machinalement');
case'IIIIILIIIIIIILLIIILIII':return array('machinalement');
case'IIIIOIIOOIIOIIIIIILOII':return array('microordinateur');
case'IIIILIIOOIIOIIIIIILOII':return array('microordinateur');
case'IIIIOIIOOIIOIIIIIOIIIL':return array('microorganisme');
case'IIIILIIOOIIOIIIIIOIIIL':return array('microorganisme');
case'IIIIIIIIOOLLOOLIIILIII':return array('miraculeusement');
case'IIIIIIIILOLLOOLIIILIII':return array('miraculeusement');
case'IIOOVLIIOILOIIIIIILIII':return array('nouveautestament');
case'IIIIIIIOOIIIILLIIILIII':return array('paradoxalement');
case'IIIIIIIOOLILIILIIILIII':return array('particulierement');
case'IIIIIIILOLILIILIIILIII':return array('particulierement');
case'IIIOOIIIIIIIIIIIIIIOII':return array('programmation');
case'IILIIIIILIIIIOLIIILIII':return array('reamenagement');
case'IILLOIILLOIIIILIIILIII':return array('reechelonnement');
case'IILLLIILLOIIIILIIILIII':return array('reechelonnement');
case'IILIIOIILIIIOOLIIILIII':return array('rencherissement');
case'IILIILIILIIIOOLIIILIII':return array('rencherissement');
case'IIIIIIOOOIIIIILIIILIII':return array('tambourinement');
case'IIIIIIIOIOIIIIIIIIIOII':return array('transformation');
default: return array();}}
?>