<?php
function gwc_coupable_haut_min_16_oo($code){switch($code){
case'ooooolimootoiooo':return array('agroalimentaires');
case'oooliitioiiomoot':return array('analytiquement');
case'oooodotioiiomoot':return array('anecdotiquement');
case'oothoooolooioiio':return array('anthropologique');
case'ooohitootooioiio':return array('architectonique');
case'ootifioiollomoot':return array('artificiellement');
case'ooooiioliooomoot':return array('assouplissement');
case'oooootooiotioiio':return array('caracteristique');
case'ootooooioiiomoot':return array('categoriquement');
case'oollootiooooiioo':return array('collectionneurs','collectionneuse');
case'oommiiooiitoiooo':return array('communautaires');
case'oomooootiiiomoot':return array('comparativement');
case'ooooootiilotiooo':return array('congratulations');
case'ooooidooohlomoot':return array('considerablement');
case'ooootitiitiooool':return array('constitutionnel');
case'oootioiiollomoot':return array('continuellement');
case'oooiiootioooollo':return array('conventionnelle');
case'ooiiohoodoooloil':return array('coucherdesoleil');
case'ooiiooooiioomoot':return array('courageusement');
case'ooiotollooooohio':return array('cristallographie');
case'ooooiiodiooomoot':return array('engourdissement');
case'oooiiioiiiooiioo':return array('enquiquineuse');
case'ooiiiioooomootol':return array('gouvernemental');
case'ooommotioolomoot':return array('grammaticalement');
case'oooiotooiiootioo':return array('nonintervention');
case'ooofootioooomoot':return array('perfectionnement');
case'ooooiiioitiooooo':return array('perquisitionner');
case'oootooioiioomoot':return array('posterieurement');
case'ooiiooiiiiioioot':return array('poursuivaient');
case'ooofoooioooolloo':return array('professionnelles');
case'ooooooooiiiomoot':return array('progressivement');
case'ooothooodootoioo':return array('prothesedentaire');
case'ooiiohoooliiotoo':return array('psychanalystes');
case'ooiiohiotoioiioo':return array('psychiatriques');
case'ooiioholooioiioo':return array('psychologiques');
case'oodootoiioooohof':return array('redacteurenchef');
case'oomoooiiohlomoot':return array('remarquablement');
case'ooooiiiiollomoot':return array('renouvellement');
case'oooiiolifiootioo':return array('requalification');
case'oooioooooomioiio':return array('socioeconomique');
case'oomotiioiioomoot':return array('somptueusement');
case'ooiiiioooioomoot':return array('souverainement');
case'ooioitiiollomoot':return array('spirituellement');
default: return array();}}
?>