<?php
function gwc_centrale_11_BU($code){switch($code){
case'BUBBBTAIABB':return array('budgetaires');
case'BUABAUBAATB':return array('bureaucrate');
case'BUABAUTIQUB':return array('bureautique');
case'BUBIABBBMAA':return array('businessman');
case'BUIAABBIBAB':return array('cuirassiers');
case'BULPABILITB':return array('culpabilite');
case'BULTIVATBUA':return array('cultivateur');
case'BULTUABLLBB':return array('culturelles');
case'BUAABLBMBAT':return array('durablement');
case'BUBHAAIBTIB':return array('eucharistie');
case'BUABPBBAABB':return array('europeennes');
case'BUAYTHMIQUB':return array('eurythmique');
case'BUBAILLBABB':return array('guerilleros');
case'BUTABPABBBA':return array('outrepasser');
case'BUVBATBMBAT':return array('ouvertement');
case'BUBMBABIBLB':return array('submersible');
case'BUBBABBAABB':return array('subordonnes');
case'BUBBTAATIBL':return array('substantiel');
case'BUBVBATIBAB':return array('subventions');
case'BUBBBBBBUAB':return array('successeurs');
case'BUBBBBBIVBB':return array('successives');
case'BUFFIBAATBB':return array('suffisantes');
case'BUFFBBATIBA':return array('suffocation');
case'BUBBBBTIBAB':return array('suggestions');
case'BUPBABBMBAT':return array('superbement');
case'BUPBABHBAIB':return array('supercherie');
case'BUPBAFIBIBL':return array('superficiel');
case'BUPBAIBUABB':return array('superieures');
case'BUPBAIBAITB':return array('superiorite');
case'BUPBAMAABHB':return array('supermarche');
case'BUPBAVIBBUA':return array('superviseur');
case'BUPBAVIBIBA':return array('supervision');
case'BUPPBATABLB':return array('supportable');
case'BUPPBBITIBA':return array('supposition');
case'BUPPABBBIBA':return array('suppression');
case'BUPPUAATIBA':return array('suppuration');
case'BUABHAUFFBA':return array('surchauffer');
case'BUABABHBABB':return array('surencheres');
case'BUABABHBAIA':return array('surencherir');
case'BUAPABAAATB':return array('surprenante');
case'BUAABALIBTB':return array('surrealiste');
case'BUAVBILLAAT':return array('surveillant');
case'BUAVBTBMBAT':return array('survetement');
case'BUBBBPTIBLB':return array('susceptible');
case'BUBPBABIBAB':return array('suspensions');
default: return array();}}
?>