<?php
function gwc_centrale_9_FA($code){switch($code){
case'FABAIBAAT':return array('fabricant');
case'FABAIQUBA':return array('fabriquer');
case'FABAIQUBB':return array('fabriques');
case'FABILITBB':return array('facilitee','facilites');
case'FABILITBA':return array('faciliter');
case'FAIBLBBBB':return array('faiblesse');
case'FAIBAIBAT':return array('faisaient');
case'FALBIFIBA':return array('falsifier');
case'FAMILIALB':return array('familiale');
case'FAMILIBAB':return array('familiere','familiers');
case'FAAATIBMB':return array('fanatisme');
case'FAATAIBIB':return array('fantaisie');
case'FAATABMBB':return array('fantasmes');
case'FABBIBULB':return array('fascicule');
case'FABBIAAAT':return array('fascinant');
case'FABBIBTBB':return array('fascistes');
case'FAUBBUABB':return array('faubourgs');
case'FAUTBUILB':return array('fauteuils');
case'FAUHJBTBA':return array('fauxjeton');
case'FAVBAABLB':return array('favorable');
case'FAVBAIBBA':return array('favoriser');
case'FAVBAIBBB':return array('favorises');
case'FAABABBBA':return array('fracasser');
case'FAABTUABA':return array('fracturer');
case'FAABILITB':return array('fragilite');
case'FAABMBATB':return array('fragments');
case'FAABAAABB':return array('fragrance');
case'FAAIBHBUA':return array('fraicheur');
case'FAAIBBUBB':return array('fraiseuse');
case'FAAMATBMB':return array('framatome');
case'FAAMBBIBB':return array('framboise');
case'FAAABAIBB':return array('francaise');
case'FAAABFBAT':return array('francfort');
case'FAAABHIBB':return array('franchise');
case'FAAABIBBB':return array('francisco');
case'FAAABBIBB':return array('francoise');
case'FAAPPAATB':return array('frappante');
case'FABLUQUBT':return array('freluquet');
case'FABQUBABB':return array('frequence');
case'FABQUBATB':return array('frequente','frequents');
case'FAIVBLITB':return array('frivolite');
case'FABATIBAB':return array('frontiere');
case'FABUBBAAB':return array('froussard');
case'FAUBTUBUH':return array('fructueux');
case'FAUBALITB':return array('frugalite');
default: return array();}}
?>