<?php
function gwc_coupable_haut_min_10_ot($code){switch($code){
case'otoiiioiio':return array('atavique');
case'othlotiomo':return array('athletisme');
case'otmooohooo':return array('atmosphere');
case'ottoioooit':return array('atteignait');
case'ottoioooot':return array('atteignant','atteignent');
case'ottootiiio':return array('attentive');
case'ottitiidoo':return array('attitudes');
case'ottoootioo':return array('attraction');
case'ottooiioot':return array('attrayant');
case'ottoihiioo':return array('attribuee','attribuer','attribues');
case'otiioioiio':return array('atypique');
case'otoooooooo':return array('etanconner','etrangeres');
case'ototmootol':return array('etatmental');
case'ototioiioo':return array('etatiques');
case'ototoiioio':return array('etatsunis');
case'othoioiioo':return array('ethniques');
case'otioiiotto':return array('etiquette');
case'otoooomoot':return array('etonnement');
case'otiidiooto':return array('etudiante','etudiants');
case'otohiliooo':return array('stabilisee','stabiliser');
case'otooioiooo':return array('stagiaires');
case'otooootioo':return array('stagnation');
case'otolioiomo':return array('stalinisme');
case'ototiooooo':return array('stationnes');
case'ototiioioo':return array('statuaire');
case'otolliooot':return array('stellionat');
case'otimiiloot':return array('stimulant');
case'otooiiholm':return array('stockholm');
case'otoohioiio':return array('strabique');
case'otootooomo':return array('stratageme');
case'otootooioo':return array('strategies');
case'otiioofoit':return array('stupefait');
case'otiioofioo':return array('stupefier');
case'otiioidito':return array('stupidite');
case'otiittooot':return array('stuttgart');
default: return array();}}
?>