<?php
function gwc_coupable_bas_min_13_ga($code){switch($code){
case'gaiiaioiiaiaa':return array('generalistes');
case'gaiiaioiaaiaa':return array('generalistes');
case'gaiiaioiiaaaa':return array('generalistes');
case'gaiiaioiaaaaa':return array('generalistes');
case'gaiiaioiiaiia':return array('generations');
case'gaiiaioaiaiia':return array('generations');
case'gaiiaioiaaiia':return array('generations');
case'gaiiaioaaaiia':return array('generations');
case'gaiiiiiiiaiii':return array('gentiment');
case'gaiiaiiiiaiii':return array('gentiment');
case'gaiiiaiiiaiii':return array('gentiment');
case'gaiiaaiiiaiii':return array('gentiment');
case'gaiiiiiiiaiia':return array('gentiment');
case'gaiiaiiiiaiia':return array('gentiment');
case'gaiiiaiiiaiia':return array('gentiment');
case'gaiiaaiiiaiia':return array('gentiment');
case'gaiiiiaiiioii':return array('gentleman');
case'gaiiaiaiiioii':return array('gentleman');
case'gaagiopiiiqaa':return array('geographique');
case'gaagiopiiaqaa':return array('geographique');
case'gaagiopiiiqoa':return array('geographique');
case'gaagiopiiaqoa':return array('geographique');
case'gaiiiioiiiqaa':return array('germanique');
case'gaiiiioiiaqaa':return array('germanique');
case'gaiiiioiiiqoa':return array('germanique');
case'gaiiiioiiaqoa':return array('germanique');
case'gagoiiiaaqaaa':return array('gigantesques');
case'gagoiiaaaqaaa':return array('gigantesques');
case'gagoiiiaaqoaa':return array('gigantesques');
case'gagoiiaaaqoaa':return array('gigantesques');
case'gaaaiaiiiioga':return array('goudronnage');
case'gaoaiaiiiioga':return array('goudronnage');
case'gaaoiaiiiioga':return array('goudronnage');
case'gaooiaiiiioga':return array('goudronnage');
case'gaabaiiioiiia':return array('gouvernants');
case'gaobaiiioiiia':return array('gouvernants');
case'gaabaiiioiiaa':return array('gouvernants');
case'gaobaiiioiiaa':return array('gouvernants');
default: return array();}}
?>