<?php
function gwc_coupable_bas_min_13_gi($code){switch($code){
case'gigoiiiaaqaaa':return array('gigantesques');
case'gigoiiaaaqaaa':return array('gigantesques');
case'gigoiiiaaqoaa':return array('gigantesques');
case'gigoiiaaaqoaa':return array('gigantesques');
case'gioiiaaaiiiai':return array('glandouiller');
case'gioiioaaiiiai':return array('glandouiller');
case'gioiiaaoiiiai':return array('glandouiller');
case'gioiioaoiiiai':return array('glandouiller');
case'gioiiaaaaiiai':return array('glandouiller');
case'gioiioaaaiiai':return array('glandouiller');
case'gioiiaaoaiiai':return array('glandouiller');
case'gioiioaoaiiai':return array('glandouiller');
case'giiaaaiiiaiii':return array('glissement');
case'giaaaaiiiaiii':return array('glissement');
case'giiaaaiiiaiia':return array('glissement');
case'giaaaaiiiaiia':return array('glissement');
case'gioiiiiiioiia':return array('grammaire');
case'gioiiiiiioaia':return array('grammaire');
case'gioiiaiaaoiii':return array('grandissant');
case'gioiioiaaoiii':return array('grandissant');
case'gioiiaaaaoiii':return array('grandissant');
case'gioiioaaaoiii':return array('grandissant');
case'gioiiaiaaoiia':return array('grandissant');
case'gioiioiaaoiia':return array('grandissant');
case'gioiiaaaaoiia':return array('grandissant');
case'gioiioaaaoiia':return array('grandissant');
case'giiabaiiiaiii':return array('grievement');
case'giaabaiiiaiii':return array('grievement');
case'giiabaiiiaiia':return array('grievement');
case'giaabaiiiaiia':return array('grievement');
case'giiiiaiiiioga':return array('griffonnage');
case'giaiiaiiiioga':return array('griffonnage');
case'giiaaiiiioiii':return array('grisonnant');
case'giaaaiiiioiii':return array('grisonnant');
case'giiaaiiiioiia':return array('grisonnant');
case'giaaaiiiioiia':return array('grisonnant');
case'giaiiiiiiaiai':return array('grommeler');
case'giaapaiiiaiii':return array('groupement');
case'giaopaiiiaiii':return array('groupement');
case'giaapaiiiaiia':return array('groupement');
case'giaopaiiiaiia':return array('groupement');
default: return array();}}
?>