<?php
function gwc_coupable_bas_min_13_ja($code){switch($code){
case'jaaiiioiiaiaa':return array('journalistes');
case'jaoiiioiiaiaa':return array('journalistes');
case'jaaiiioiaaiaa':return array('journalistes');
case'jaoiiioiaaiaa':return array('journalistes');
case'jaaiiioiiaaaa':return array('journalistes');
case'jaoiiioiiaaaa':return array('journalistes');
case'jaaiiioiaaaaa':return array('journalistes');
case'jaoiiioiaaaaa':return array('journalistes');
case'jaiiaiaiiaiia':return array('juridictions');
case'jaiaaiaiiaiia':return array('juridictions');
case'jaiioiaiiaiia':return array('juridictions');
case'jaiaoiaiiaiia':return array('juridictions');
case'jaiiaaaiiaiia':return array('juridictions');
case'jaiaaaaiiaiia':return array('juridictions');
case'jaiioaaiiaiia':return array('juridictions');
case'jaiaoaaiiaiia':return array('juridictions');
case'jaiiaiaaiaiia':return array('juridictions');
case'jaiaaiaaiaiia':return array('juridictions');
case'jaiioiaaiaiia':return array('juridictions');
case'jaiaoiaaiaiia':return array('juridictions');
case'jaiiaaaaiaiia':return array('juridictions');
case'jaiaaaaaiaiia':return array('juridictions');
case'jaiioaaaiaiia':return array('juridictions');
case'jaiaoaaaiaiia':return array('juridictions');
case'jaiiaiaiaaiia':return array('juridictions');
case'jaiaaiaiaaiia':return array('juridictions');
case'jaiioiaiaaiia':return array('juridictions');
case'jaiaoiaiaaiia':return array('juridictions');
case'jaiiaaaiaaiia':return array('juridictions');
case'jaiaaaaiaaiia':return array('juridictions');
case'jaiioaaiaaiia':return array('juridictions');
case'jaiaoaaiaaiia':return array('juridictions');
case'jaiiaiaaaaiia':return array('juridictions');
case'jaiaaiaaaaiia':return array('juridictions');
case'jaiioiaaaaiia':return array('juridictions');
case'jaiaoiaaaaiia':return array('juridictions');
case'jaiiaaaaaaiia':return array('juridictions');
case'jaiaaaaaaaiia':return array('juridictions');
case'jaiioaaaaaiia':return array('juridictions');
case'jaiaoaaaaaiia':return array('juridictions');
default: return array();}}
?>