<?php
function gwc_coupable_haut_maj_18_CC($code){switch($code){
case'CCAAAAAIIIAIIAMAAT':return array('geographiquement');
case'CCACAAAIIIAIIAMAAT':return array('geographiquement');
case'CCAAAAAIIIAIICMAAT':return array('geographiquement');
case'CCACAAAIIIAIICMAAT':return array('geographiquement');
case'CCAAAAAIIIAIIAMCAT':return array('geographiquement');
case'CCACAAAIIIAIIAMCAT':return array('geographiquement');
case'CCAAAAAIIIAIICMCAT':return array('geographiquement');
case'CCACAAAIIIAIICMCAT':return array('geographiquement');
case'CCIAIITICIAIIAMAAT':return array('scientifiquement');
case'CCICIITICIAIIAMAAT':return array('scientifiquement');
case'CCIAIITICIAIICMAAT':return array('scientifiquement');
case'CCICIITICIAIICMAAT':return array('scientifiquement');
case'CCIAIITICIAIIAMCAT':return array('scientifiquement');
case'CCICIITICIAIIAMCAT':return array('scientifiquement');
case'CCIAIITICIAIICMCAT':return array('scientifiquement');
case'CCICIITICIAIICMCAT':return array('scientifiquement');
case'CCIAATICIAIIAMAIIT':return array('scientifiquement');
case'CCICATICIAIIAMAIIT':return array('scientifiquement');
case'CCIAATICIAIICMAIIT':return array('scientifiquement');
case'CCICATICIAIICMAIIT':return array('scientifiquement');
case'CCIAATICIAIIAMCIIT':return array('scientifiquement');
case'CCICATICIAIIAMCIIT':return array('scientifiquement');
case'CCIAATICIAIICMCIIT':return array('scientifiquement');
case'CCICATICIAIICMCIIT':return array('scientifiquement');
case'CCAIIAIIIAIIAAMAAT':return array('scrupuleusement');
case'CCAIIAIIICIIAAMAAT':return array('scrupuleusement');
case'CCAIIAIIIAIICAMAAT':return array('scrupuleusement');
case'CCAIIAIIICIICAMAAT':return array('scrupuleusement');
case'CCAIIAIIIAIIACMAAT':return array('scrupuleusement');
case'CCAIIAIIICIIACMAAT':return array('scrupuleusement');
case'CCAIIAIIIAIICCMAAT':return array('scrupuleusement');
case'CCAIIAIIICIICCMAAT':return array('scrupuleusement');
case'CCAIIAIIIAIIAAMCAT':return array('scrupuleusement');
case'CCAIIAIIICIIAAMCAT':return array('scrupuleusement');
case'CCAIIAIIIAIICAMCAT':return array('scrupuleusement');
case'CCAIIAIIICIICAMCAT':return array('scrupuleusement');
case'CCAIIAIIIAIIACMCAT':return array('scrupuleusement');
case'CCAIIAIIICIIACMCAT':return array('scrupuleusement');
case'CCAIIAIIIAIICCMCAT':return array('scrupuleusement');
case'CCAIIAIIICIICCMCAT':return array('scrupuleusement');
default: return array();}}
?>