<?php
function gwc_coupable_haut_maj_6_CT($code){switch($code){
case'CTAAIA':return array('etable','stable');
case'CTAAIC':return array('etable','stable');
case'CTAAII':return array('etabli','etron','stern','stock');
case'CTAAAA':return array('etages','etapes','etonne','stades','stages','stands','stoppe','stores','stress');
case'CTACAA':return array('etages','stages','stefan','stress');
case'CTAACA':return array('etages','etapes','stades','stages','stores','stress');
case'CTACCA':return array('etages','etoffe','stages','stress');
case'CTAAAC':return array('etages','etapes','etonne','stades','stages','stands','stoppe','stores','stress');
case'CTACAC':return array('etages','stages','stress');
case'CTAACC':return array('etages','etapes','stades','stages','stores','stress');
case'CTACCC':return array('etages','etoffe','stages','stress');
case'CTAIII':return array('etain','stein');
case'CTAIAA':return array('etaler','etalon','etrier');
case'CTAICA':return array('etaler','etrier');
case'CTAMAA':return array('etamer');
case'CTAMCA':return array('etamer');
case'CTAIIA':return array('etang','etaye','etoile','stalle','stand','steve');
case'CTAIIC':return array('etang','etaye','etoile','stalle','steve');
case'CTAIIT':return array('etant');
case'CTIAAA':return array('etions','etirer');
case'CTIAAC':return array('etions');
case'CTIACA':return array('etirer');
case'CTAAIT':return array('etroit');
case'CTIIAA':return array('etude');
case'CTIIAC':return array('etude');
case'CTATII':return array('statu');
case'CTCCAA':return array('stefan');
case'CTCIII':return array('stein');
case'CTCAII':return array('stern');
case'CTCIIA':return array('steve');
case'CTCIIC':return array('steve');
case'CTIAII':return array('stick');
case'CTICII':return array('stick');
case'CTACII':return array('stock');
case'CTAATA':return array('strate');
case'CTAATC':return array('strate');
case'CTAIAT':return array('strict');
case'CTAICT':return array('strict');
case'CTIIIA':return array('style','stylo');
case'CTIIIC':return array('style');
default: return array();}}
?>