<?php
function gwc_coupable_haut_min_5_ho($code){switch($code){
case'hohii':return array('baby');
case'hooii':return array('back','beau','bock');
case'hoolo':return array('bacle');
case'hoooo':return array('bacon','bagne','banco','bancs','barge','baron','barre','basee','baser','bases','basse','berge','berne','bongo','bonne','borna','borne','bosse','hagen','happe','harpe','heron','heros');
case'hodoo':return array('baden','badge','hades','kadar');
case'hoffo':return array('baffe');
case'hoioo':return array('bains','beige','boire','brice','brise','haine');
case'hohoo':return array('baker','bebes','bekaa','habre');
case'holoi':return array('balai');
case'hollo':return array('balle','belle','halle');
case'holto':return array('balte','halte');
case'hoool':return array('banal','bocal');
case'hoodo':return array('bande','barde','bonde','bonds','borde','bords','honda');
case'hooio':return array('banjo','benin','benir','boris');
case'hooho':return array('barbe','hache','herbe','hoche');
case'hooil':return array('baril');
case'hotio':return array('batir');
case'hotoo':return array('baton','betes','beton','hater','hotes');
case'hoiio':return array('bave','bouc','boue','boxe','boys','brun','have');
case'hozoo':return array('bazar','kazan');
case'hooot':return array('becot','beret','brest','horst');
case'holoo':return array('beler','belge','haler','helas','heler');
case'hotto':return array('bette','botte');
case'hoito':return array('boite');
case'homho':return array('bombe');
case'hooto':return array('bonte','hante','honte');
case'hotho':return array('botha');
case'hoiim':return array('boum');
case'hoiit':return array('bout','brut','haut');
case'hoomo':return array('brame');
case'hoooh':return array('break','kanak','krach');
case'hoofo':return array('brefs');
case'hoiho':return array('bribe');
case'hoido':return array('bride');
case'hohit':return array('habit');
case'hoiti':return array('haiti');
case'homoo':return array('hampe');
case'hoooi':return array('hanoi','henri');
case'hohdo':return array('hebdo');
case'hommo':return array('homme');
case'hotol':return array('hotel');
case'hofho':return array('kafka');
default: return array();}}
?>